import type {
  CrmDocument,
  CrmKpiMetric,
  CrmOrder,
  CrmTask,
  Customer360,
  DeliveryNote,
  PipelineDeal,
  PipelineStage,
} from "./types";

export const CRM_KPI_METRICS: readonly CrmKpiMetric[] = [
  {
    id: "customers",
    label: "Customers",
    value: "1,284",
    caption: "Active relationships",
    delta: { value: "+42", positive: true },
  },
  {
    id: "companies",
    label: "Companies",
    value: "318",
    caption: "Account organizations",
    delta: { value: "+11", positive: true },
  },
  {
    id: "leads",
    label: "Leads",
    value: "96",
    caption: "New this month",
    delta: { value: "+8%", positive: true },
  },
  {
    id: "deals",
    label: "Deals",
    value: "54",
    caption: "Open pipeline",
    delta: { amount: 1_240_000, currency: "EUR", compact: true, positive: true },
  },
  {
    id: "revenue",
    label: "Revenue",
    value: 842500,
    currency: "EUR",
    caption: "Won YTD",
    delta: { value: "+14.2%", positive: true },
  },
  {
    id: "projects",
    label: "Active Projects",
    value: "37",
    caption: "Delivery in flight",
    delta: { value: "+3", positive: true },
  },
  {
    id: "tasks",
    label: "Open Tasks",
    value: "128",
    caption: "Across CRM + delivery",
    delta: { value: "-12", positive: true },
  },
  {
    id: "ai-health",
    label: "AI Health Score",
    value: "91 / 100",
    caption: "Relationship quality signal",
    delta: { value: "+2", positive: true },
  },
];

export const PIPELINE_STAGES: readonly {
  readonly id: PipelineStage;
  readonly label: string;
}[] = [
  { id: "lead", label: "Lead" },
  { id: "qualified", label: "Qualified" },
  { id: "proposal", label: "Proposal" },
  { id: "negotiation", label: "Negotiation" },
  { id: "won", label: "Won" },
  { id: "lost", label: "Lost" },
];

export const CUSTOMER_360: Customer360 = {
  id: "cust-nordlicht",
  name: "Elena Vogt",
  email: "elena.vogt@nordlicht.de",
  phone: "+49 89 1234 5678",
  status: "active",
  company: {
    id: "co-nordlicht",
    name: "Nordlicht GmbH",
    industry: "Logistics",
    website: "nordlicht.de",
    city: "Munich",
    country: "DE",
  },
  contacts: [
    {
      id: "ct-1",
      name: "Elena Vogt",
      role: "CEO",
      email: "elena.vogt@nordlicht.de",
      phone: "+49 89 1234 5678",
    },
    {
      id: "ct-2",
      name: "Jonas Keller",
      role: "Procurement",
      email: "jonas.keller@nordlicht.de",
      phone: "+49 89 1234 5690",
    },
  ],
  orders: ["ORD-2026-084", "ORD-2026-061"],
  invoices: ["INV-2026-1001", "INV-2026-0942"],
  lieferscheine: ["LS-2026-221", "LS-2026-198"],
  payments: [
    { id: "pay-1", amount: 12400, at: "2026-07-12", status: "settled" },
    { id: "pay-2", amount: 8900, at: "2026-06-28", status: "settled" },
  ],
  documents: ["doc-quote-12", "doc-contract-4", "doc-ls-221"],
  timeline: [
    {
      id: "tl-1",
      at: "2026-07-29T10:00:00Z",
      title: "Proposal sent",
      detail: "Q3 logistics automation package shared with Elena.",
    },
    {
      id: "tl-2",
      at: "2026-07-22T15:30:00Z",
      title: "Delivery completed",
      detail: "LS-2026-221 signed and archived.",
    },
    {
      id: "tl-3",
      at: "2026-07-10T09:15:00Z",
      title: "Meeting",
      detail: "Discovery call covering warehouse routing pain points.",
    },
  ],
  activities: [
    {
      id: "act-1",
      at: "2026-07-28T16:00:00Z",
      kind: "Call",
      summary: "Follow-up on negotiation terms (net-30).",
    },
    {
      id: "act-2",
      at: "2026-07-25T11:20:00Z",
      kind: "Email",
      summary: "Sent revised proposal PDF and pricing matrix.",
    },
  ],
  notes: [
    {
      id: "note-1",
      at: "2026-07-28T16:20:00Z",
      author: "Sara M.",
      body: "Decision maker is Elena; Jonas owns commercial review.",
    },
  ],
  aiSummary:
    "Nordlicht is an expansion-ready logistics account with strong payment history, active delivery volume, and a late-stage automation deal. Priority: close negotiation this week and schedule onboarding kickoff.",
  communicationHistory: [
    {
      id: "com-1",
      at: "2026-07-28T16:00:00Z",
      channel: "Voice",
      direction: "outbound",
      subject: "Negotiation follow-up",
      preview: "Confirmed net-30 preference and Q3 start window.",
    },
    {
      id: "com-2",
      at: "2026-07-25T11:20:00Z",
      channel: "Email",
      direction: "outbound",
      subject: "Revised proposal",
      preview: "Attached pricing matrix and SLA options.",
    },
  ],
  healthScore: 92,
};

export const PIPELINE_DEALS: readonly PipelineDeal[] = [
  {
    id: "deal-1",
    title: "Warehouse automation",
    company: "Nordlicht GmbH",
    value: 84000,
    currency: "EUR",
    owner: "Sara M.",
    stage: "negotiation",
    probability: 70,
    closeDate: "2026-08-15",
  },
  {
    id: "deal-2",
    title: "Retail POS rollout",
    company: "Helios Markets",
    value: 42000,
    currency: "EUR",
    owner: "Tom K.",
    stage: "proposal",
    probability: 45,
    closeDate: "2026-08-28",
  },
  {
    id: "deal-3",
    title: "Creator brand kit",
    company: "Lumen Studio",
    value: 12500,
    currency: "EUR",
    owner: "Maya R.",
    stage: "qualified",
    probability: 35,
    closeDate: "2026-09-05",
  },
  {
    id: "deal-4",
    title: "Hotel guest CRM",
    company: "Alpenblick Hotels",
    value: 56000,
    currency: "EUR",
    owner: "Sara M.",
    stage: "lead",
    probability: 20,
    closeDate: "2026-09-20",
  },
  {
    id: "deal-5",
    title: "Agency retainer",
    company: "Orbit Agency",
    value: 28000,
    currency: "EUR",
    owner: "Tom K.",
    stage: "won",
    probability: 100,
    closeDate: "2026-07-18",
  },
  {
    id: "deal-6",
    title: "Laundry route OS",
    company: "Frischwäsche KG",
    value: 19000,
    currency: "EUR",
    owner: "Maya R.",
    stage: "lost",
    probability: 0,
    closeDate: "2026-07-05",
  },
  {
    id: "deal-7",
    title: "E-com fulfillment",
    company: "Nova Shop SE",
    value: 67000,
    currency: "EUR",
    owner: "Sara M.",
    stage: "proposal",
    probability: 50,
    closeDate: "2026-08-22",
  },
  {
    id: "deal-8",
    title: "Law firm vault",
    company: "Weber & Partner",
    value: 31000,
    currency: "EUR",
    owner: "Tom K.",
    stage: "qualified",
    probability: 40,
    closeDate: "2026-09-01",
  },
];

export const CRM_ORDERS: readonly CrmOrder[] = [
  {
    id: "ord-1",
    number: "ORD-2026-084",
    customerId: "cust-nordlicht",
    customerName: "Nordlicht GmbH",
    status: "in_fulfillment",
    currency: "EUR",
    createdAt: "2026-07-20",
    lines: [
      {
        id: "ol-1",
        kind: "service",
        name: "Route optimization setup",
        qty: 1,
        unitPrice: 6800,
        discountPct: 5,
        taxPct: 19,
      },
      {
        id: "ol-2",
        kind: "product",
        name: "Scanner kits",
        qty: 12,
        unitPrice: 180,
        discountPct: 0,
        taxPct: 19,
      },
    ],
  },
  {
    id: "ord-2",
    number: "ORD-2026-061",
    customerId: "cust-nordlicht",
    customerName: "Nordlicht GmbH",
    status: "delivered",
    currency: "EUR",
    createdAt: "2026-06-12",
    lines: [
      {
        id: "ol-3",
        kind: "service",
        name: "Onboarding package",
        qty: 1,
        unitPrice: 4200,
        discountPct: 0,
        taxPct: 19,
      },
    ],
  },
  {
    id: "ord-3",
    number: "ORD-2026-091",
    customerId: "cust-helios",
    customerName: "Helios Markets",
    status: "confirmed",
    currency: "EUR",
    createdAt: "2026-07-26",
    lines: [
      {
        id: "ol-4",
        kind: "product",
        name: "POS terminals",
        qty: 8,
        unitPrice: 890,
        discountPct: 10,
        taxPct: 19,
      },
      {
        id: "ol-5",
        kind: "service",
        name: "Install & training",
        qty: 1,
        unitPrice: 2400,
        discountPct: 0,
        taxPct: 19,
      },
    ],
  },
];

export const DELIVERY_NOTES: readonly DeliveryNote[] = [
  {
    id: "dn-1",
    number: "LS-2026-221",
    orderNumber: "ORD-2026-084",
    customerName: "Nordlicht GmbH",
    kind: "delivery",
    driver: "M. Brandt",
    vehicle: "VAN-DE-441",
    trackingStatus: "en_route",
    scheduledAt: "2026-07-30T08:00:00Z",
    signatureReady: true,
    qrReady: true,
    barcodeReady: true,
  },
  {
    id: "dn-2",
    number: "LS-2026-198",
    orderNumber: "ORD-2026-061",
    customerName: "Nordlicht GmbH",
    kind: "delivery",
    driver: "A. Schulz",
    vehicle: "VAN-DE-228",
    trackingStatus: "completed",
    scheduledAt: "2026-07-22T09:30:00Z",
    signatureReady: true,
    qrReady: true,
    barcodeReady: true,
  },
  {
    id: "dn-3",
    number: "LS-2026-230",
    orderNumber: "ORD-2026-091",
    customerName: "Helios Markets",
    kind: "pickup",
    driver: "Depot desk",
    vehicle: "—",
    trackingStatus: "scheduled",
    scheduledAt: "2026-08-02T14:00:00Z",
    signatureReady: true,
    qrReady: true,
    barcodeReady: true,
  },
];

export const CRM_DOCUMENTS: readonly CrmDocument[] = [
  {
    id: "doc-quote-12",
    kind: "quote",
    title: "Q3 automation quote",
    customerName: "Nordlicht GmbH",
    updatedAt: "2026-07-25",
    status: "sent",
  },
  {
    id: "doc-contract-4",
    kind: "contract",
    title: "Master service agreement",
    customerName: "Nordlicht GmbH",
    updatedAt: "2026-06-01",
    status: "signed",
  },
  {
    id: "doc-inv-1001",
    kind: "invoice",
    title: "INV-2026-1001",
    customerName: "Nordlicht GmbH",
    updatedAt: "2026-07-12",
    status: "paid",
  },
  {
    id: "doc-ls-221",
    kind: "lieferschein",
    title: "LS-2026-221",
    customerName: "Nordlicht GmbH",
    updatedAt: "2026-07-30",
    status: "in_transit",
  },
  {
    id: "doc-po-18",
    kind: "purchase_order",
    title: "PO-Scanner kits",
    customerName: "Supplier — ScanTech",
    updatedAt: "2026-07-18",
    status: "open",
  },
  {
    id: "doc-rc-9",
    kind: "receipt",
    title: "Payment receipt Jul 12",
    customerName: "Nordlicht GmbH",
    updatedAt: "2026-07-12",
    status: "filed",
  },
];

export const CRM_TASKS: readonly CrmTask[] = [
  {
    id: "task-1",
    title: "Send revised SLA",
    kind: "follow_up",
    status: "open",
    dueAt: "2026-07-31T10:00:00Z",
    relatedTo: "Nordlicht GmbH",
    owner: "Sara M.",
  },
  {
    id: "task-2",
    title: "Kickoff meeting",
    kind: "meeting",
    status: "open",
    dueAt: "2026-08-04T13:00:00Z",
    relatedTo: "Orbit Agency",
    owner: "Tom K.",
  },
  {
    id: "task-3",
    title: "Delivery reminder",
    kind: "reminder",
    status: "in_progress",
    dueAt: "2026-07-30T07:30:00Z",
    relatedTo: "LS-2026-221",
    owner: "Ops Desk",
  },
  {
    id: "task-4",
    title: "Prepare POS demo",
    kind: "task",
    status: "open",
    dueAt: "2026-08-01T16:00:00Z",
    relatedTo: "Helios Markets",
    owner: "Maya R.",
  },
];
