import type { AgentDefinition } from "./types";

export const CORE_AGENTS: readonly AgentDefinition[] = [
  {
    id: "agent.operations",
    key: "operations",
    name: "Operations Agent",
    description: "Monitors operational throughput and bottlenecks",
    capabilities: ["monitoring", "analysis", "planning"],
    defaultTools: ["metrics.query", "workflow.trigger"],
    status: "registered",
    version: "1.0.0",
  },
  {
    id: "agent.revenue",
    key: "revenue",
    name: "Revenue Agent",
    description: "Tracks revenue signals, forecasts, and opportunities",
    capabilities: ["analysis", "planning"],
    defaultTools: ["finance.summary", "forecast.run"],
    status: "registered",
    version: "1.0.0",
  },
  {
    id: "agent.customer",
    key: "customer",
    name: "Customer Agent",
    description: "Understands retention, satisfaction, and support themes",
    capabilities: ["communication", "analysis"],
    defaultTools: ["crm.summary", "support.trends"],
    status: "registered",
    version: "1.0.0",
  },
  {
    id: "agent.compliance",
    key: "compliance",
    name: "Compliance Agent",
    description: "Flags policy, regulatory, and process risks",
    capabilities: ["compliance", "monitoring"],
    defaultTools: ["policy.check", "audit.trail"],
    status: "registered",
    version: "1.0.0",
  },
  {
    id: "agent.scheduling",
    key: "scheduling",
    name: "Scheduling Agent",
    description: "Optimizes calendars, shifts, and capacity windows",
    capabilities: ["planning", "automation"],
    defaultTools: ["calendar.query", "capacity.plan"],
    status: "registered",
    version: "1.0.0",
  },
  {
    id: "agent.insights",
    key: "insights",
    name: "Insights Agent",
    description: "Synthesizes cross-module analytics into actions",
    capabilities: ["analysis", "planning"],
    defaultTools: ["analytics.query", "report.compose"],
    status: "registered",
    version: "1.0.0",
  },
] as const;
