import type {
  DocumentActivity,
  DocumentFolder,
  DocumentsKpi,
  KnowledgeArticle,
  KnowledgeDocument,
} from "./types";

export const DOCUMENTS_KPIS: readonly DocumentsKpi[] = [
  {
    id: "documents",
    label: "Documents",
    value: 1248,
    caption: "Sample · across folders",
    delta: { positive: true, count: 36 },
  },
  {
    id: "folders",
    label: "Folders",
    value: 86,
    caption: "Sample · including smart collections",
    delta: { positive: true, count: 4 },
  },
  {
    id: "storage",
    label: "Storage Used",
    value: 0,
    valueBytes: Math.round(42.6 * 1024 * 1024 * 1024),
    caption: "Sample · of illustrative plan",
    delta: { positive: false, sizeBytes: Math.round(1.2 * 1024 * 1024 * 1024) },
  },
  {
    id: "shared",
    label: "Shared Documents",
    value: 318,
    caption: "Sample · org + department + users",
    delta: { positive: true, count: 12 },
  },
  {
    id: "activity",
    label: "Recent Activity",
    value: 94,
    caption: "Sample · last 24 hours",
    delta: { positive: true, count: 18 },
  },
  {
    id: "indexed",
    label: "AI Indexed",
    value: 1102,
    caption: "Sample · AI search not connected",
    delta: { positive: true, percent: 88 },
  },
  {
    id: "approvals",
    label: "Pending Approvals",
    value: 9,
    caption: "Sample · automation not connected",
    delta: { positive: true, count: -3 },
  },
  {
    id: "score",
    label: "Knowledge Score",
    value: 87,
    caption: "Sample · coverage illustration",
    delta: { positive: true, count: 2 },
  },
];

export const DOCUMENT_FOLDERS: readonly DocumentFolder[] = [
  { id: "f-root-policies", name: "Policies", parentId: null, pinned: true, category: "Governance" },
  { id: "f-root-finance", name: "Finance", parentId: null, favorite: true, category: "Finance" },
  { id: "f-root-crm", name: "CRM Records", parentId: null, category: "CRM" },
  { id: "f-root-creator", name: "Creator Assets", parentId: null, category: "Marketing" },
  { id: "f-root-hr", name: "People Ops", parentId: null, category: "HR" },
  { id: "f-fin-invoices", name: "Invoices", parentId: "f-root-finance", tags: ["billing"] },
  { id: "f-fin-tax", name: "Tax Packs", parentId: "f-root-finance", tags: ["tax"] },
  { id: "f-crm-contracts", name: "Contracts", parentId: "f-root-crm", pinned: true },
  { id: "f-crm-proposals", name: "Proposals", parentId: "f-root-crm" },
  {
    id: "sc-needs-review",
    name: "Needs Review",
    parentId: null,
    smart: true,
    collection: true,
    tags: ["review"],
    category: "Smart",
  },
  {
    id: "sc-ai-indexed",
    name: "AI Indexed",
    parentId: null,
    smart: true,
    collection: true,
    category: "Smart",
  },
  {
    id: "col-onboarding",
    name: "Customer Onboarding Pack",
    parentId: null,
    collection: true,
    favorite: true,
    category: "Collections",
  },
];

function versions(
  base: string,
  sizes: readonly number[],
): KnowledgeDocument["versions"] {
  return sizes.map((sizeBytes, i) => ({
    id: `${base}-v${i + 1}`,
    version: `v${i + 1}.0`,
    createdAt: `2026-0${Math.max(1, 7 - i)}-1${i}T10:00:00Z`,
    author: i === 0 ? "Alex Morgan" : i === 1 ? "Sam Rivera" : "Jordan Lee",
    notes: i === 0 ? "Current published revision." : "Historical revision.",
    sizeBytes,
  }));
}

export const KNOWLEDGE_DOCUMENTS: readonly KnowledgeDocument[] = [
  {
    id: "doc-policy-security",
    name: "Information Security Policy.pdf",
    fileType: "pdf",
    sizeBytes: 1_240_000,
    owner: "Alex Morgan",
    createdAt: "2026-03-12T09:00:00Z",
    updatedAt: "2026-07-28T14:20:00Z",
    category: "Policy",
    department: "Security",
    status: "approved",
    retention: "7 years",
    version: "v3.0",
    tags: ["security", "compliance", "policy"],
    folderId: "f-root-policies",
    favorite: true,
    pinned: true,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "organization",
    linkedModules: ["automation", "hr"],
    pages: 18,
    previewText:
      "This policy defines AGXORA controls for access, encryption, retention, and incident response across the Business OS.",
    versions: versions("doc-policy-security", [1_240_000, 1_180_000, 980_000]),
    ai: {
      summary: "Enterprise security policy covering RBAC, encryption, and retention baselines.",
      keywords: ["RBAC", "encryption", "retention", "incident response"],
      classification: "Governance / Policy",
      suggestedTags: ["iso27001", "access-control"],
      suggestedFolder: "Policies",
      relatedDocumentIds: ["doc-process-onboarding", "doc-faq-access"],
      translationReady: true,
      ocrReady: true,
    },
  },
  {
    id: "doc-invoice-pack",
    name: "Q2 Invoice Export.xlsx",
    fileType: "excel",
    sizeBytes: 890_000,
    owner: "Sam Rivera",
    createdAt: "2026-07-01T08:00:00Z",
    updatedAt: "2026-07-29T11:10:00Z",
    category: "Finance Pack",
    department: "Finance",
    status: "in_review",
    retention: "10 years",
    version: "v2.0",
    tags: ["invoice", "q2", "export"],
    folderId: "f-fin-invoices",
    favorite: false,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "department",
    linkedModules: ["finance", "automation"],
    pages: 1,
    previewText: "Ledger-ready invoice lines for Q2 with customer, tax, and payment columns.",
    versions: versions("doc-invoice-pack", [890_000, 860_000]),
    ai: {
      summary: "Finance workbook of Q2 invoices pending controller review.",
      keywords: ["invoice", "VAT", "AR"],
      classification: "Finance / Export",
      suggestedTags: ["accounts-receivable", "tax"],
      suggestedFolder: "Finance / Invoices",
      relatedDocumentIds: ["doc-tax-memo"],
      translationReady: false,
      ocrReady: false,
    },
  },
  {
    id: "doc-tax-memo",
    name: "VAT Memo DE.md",
    fileType: "markdown",
    sizeBytes: 42_000,
    owner: "Jordan Lee",
    createdAt: "2026-06-18T10:00:00Z",
    updatedAt: "2026-07-20T16:40:00Z",
    category: "Tax",
    department: "Finance",
    status: "approved",
    retention: "10 years",
    version: "v1.2",
    tags: ["vat", "germany", "memo"],
    folderId: "f-fin-tax",
    favorite: true,
    pinned: false,
    shared: false,
    archived: false,
    trashed: false,
    shareScope: "private",
    linkedModules: ["finance"],
    pages: 4,
    previewText: "Internal guidance on reverse charge and OSS for EU B2B invoices.",
    versions: versions("doc-tax-memo", [42_000, 38_000]),
    ai: {
      summary: "German VAT operating memo for EU B2B invoicing scenarios.",
      keywords: ["VAT", "OSS", "reverse charge"],
      classification: "Finance / Tax",
      suggestedTags: ["compliance", "eu"],
      suggestedFolder: "Finance / Tax Packs",
      relatedDocumentIds: ["doc-invoice-pack"],
      translationReady: true,
      ocrReady: false,
    },
  },
  {
    id: "doc-contract-acme",
    name: "Acme Master Service Agreement.docx",
    fileType: "word",
    sizeBytes: 620_000,
    owner: "Alex Morgan",
    createdAt: "2026-05-02T12:00:00Z",
    updatedAt: "2026-07-27T09:30:00Z",
    category: "Contract",
    department: "Sales",
    status: "in_review",
    retention: "Contract + 6 years",
    version: "v4.0",
    tags: ["msa", "acme", "legal"],
    folderId: "f-crm-contracts",
    favorite: true,
    pinned: true,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "specific_users",
    linkedModules: ["crm", "automation"],
    pages: 22,
    previewText: "MSA covering SLAs, data processing, liability caps, and renewal terms for Acme GmbH.",
    versions: versions("doc-contract-acme", [620_000, 600_000, 540_000]),
    ai: {
      summary: "Customer MSA in legal review with SLA and DPA annexes.",
      keywords: ["MSA", "SLA", "DPA", "liability"],
      classification: "CRM / Contract",
      suggestedTags: ["legal", "renewal"],
      suggestedFolder: "CRM Records / Contracts",
      relatedDocumentIds: ["doc-proposal-acme"],
      duplicateOfId: undefined,
      translationReady: true,
      ocrReady: true,
    },
  },
  {
    id: "doc-proposal-acme",
    name: "Acme Enterprise Proposal.pptx",
    fileType: "powerpoint",
    sizeBytes: 4_200_000,
    owner: "Sam Rivera",
    createdAt: "2026-07-10T15:00:00Z",
    updatedAt: "2026-07-26T18:00:00Z",
    category: "Proposal",
    department: "Sales",
    status: "draft",
    retention: "3 years",
    version: "v1.0",
    tags: ["proposal", "enterprise"],
    folderId: "f-crm-proposals",
    favorite: false,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "department",
    linkedModules: ["crm", "creator"],
    pages: 14,
    previewText: "Pitch deck outlining AGXORA Business OS modules, ROI, and implementation plan.",
    versions: versions("doc-proposal-acme", [4_200_000]),
    ai: {
      summary: "Sales proposal deck for Acme enterprise rollout.",
      keywords: ["ROI", "implementation", "modules"],
      classification: "CRM / Proposal",
      suggestedTags: ["pitch", "enterprise"],
      suggestedFolder: "CRM Records / Proposals",
      relatedDocumentIds: ["doc-contract-acme", "doc-brand-guide"],
      translationReady: true,
      ocrReady: false,
    },
  },
  {
    id: "doc-brand-guide",
    name: "Brand System Guide.pdf",
    fileType: "pdf",
    sizeBytes: 8_100_000,
    owner: "Casey Ng",
    createdAt: "2026-04-01T09:00:00Z",
    updatedAt: "2026-07-15T13:00:00Z",
    category: "Brand",
    department: "Marketing",
    status: "approved",
    retention: "5 years",
    version: "v2.1",
    tags: ["brand", "design", "creator"],
    folderId: "f-root-creator",
    favorite: true,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "organization",
    linkedModules: ["creator"],
    pages: 36,
    previewText: "Typography, color tokens, motion guidance, and campaign asset rules for Creator Studio.",
    versions: versions("doc-brand-guide", [8_100_000, 7_800_000]),
    ai: {
      summary: "Brand system reference for Creator Studio campaigns.",
      keywords: ["typography", "tokens", "motion"],
      classification: "Marketing / Brand",
      suggestedTags: ["design-system", "assets"],
      suggestedFolder: "Creator Assets",
      relatedDocumentIds: ["doc-campaign-brief"],
      translationReady: false,
      ocrReady: true,
    },
  },
  {
    id: "doc-campaign-brief",
    name: "Summer Campaign Brief.json",
    fileType: "json",
    sizeBytes: 18_000,
    owner: "Casey Ng",
    createdAt: "2026-07-05T11:00:00Z",
    updatedAt: "2026-07-25T10:20:00Z",
    category: "Brief",
    department: "Marketing",
    status: "approved",
    retention: "2 years",
    version: "v1.0",
    tags: ["campaign", "brief"],
    folderId: "f-root-creator",
    favorite: false,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "department",
    linkedModules: ["creator", "automation"],
    pages: 1,
    previewText: '{"campaign":"summer-launch","channels":["linkedin","email"],"cta":"Book demo"}',
    versions: versions("doc-campaign-brief", [18_000]),
    ai: {
      summary: "Structured campaign brief consumed by Creator Studio pipelines.",
      keywords: ["campaign", "channels", "CTA"],
      classification: "Marketing / Brief",
      suggestedTags: ["linkedin", "email"],
      suggestedFolder: "Creator Assets",
      relatedDocumentIds: ["doc-brand-guide"],
      translationReady: false,
      ocrReady: false,
    },
  },
  {
    id: "doc-process-onboarding",
    name: "Employee Onboarding Process.md",
    fileType: "markdown",
    sizeBytes: 28_000,
    owner: "Riley Chen",
    createdAt: "2026-02-14T08:00:00Z",
    updatedAt: "2026-07-22T12:00:00Z",
    category: "Process",
    department: "People",
    status: "approved",
    retention: "5 years",
    version: "v2.0",
    tags: ["onboarding", "hr", "process"],
    folderId: "f-root-hr",
    favorite: false,
    pinned: true,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "organization",
    linkedModules: ["hr", "automation"],
    pages: 6,
    previewText: "Step-by-step onboarding with IT provisioning, policy ack, and buddy assignment.",
    versions: versions("doc-process-onboarding", [28_000, 24_000]),
    ai: {
      summary: "People Ops onboarding process linked to Automation approval gates.",
      keywords: ["onboarding", "provisioning", "buddy"],
      classification: "HR / Process",
      suggestedTags: ["checklist", "automation"],
      suggestedFolder: "People Ops",
      relatedDocumentIds: ["doc-policy-security", "doc-faq-access"],
      translationReady: true,
      ocrReady: false,
    },
  },
  {
    id: "doc-faq-access",
    name: "Access FAQ.txt",
    fileType: "text",
    sizeBytes: 9_400,
    owner: "Riley Chen",
    createdAt: "2026-07-08T09:00:00Z",
    updatedAt: "2026-07-28T08:10:00Z",
    category: "FAQ",
    department: "IT",
    status: "approved",
    retention: "2 years",
    version: "v1.1",
    tags: ["faq", "access", "support"],
    folderId: "col-onboarding",
    favorite: false,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "organization",
    linkedModules: ["hr", "projects"],
    pages: 2,
    previewText: "How do I request module access? Who approves external shares? How long until SSO sync?",
    versions: versions("doc-faq-access", [9_400, 8_800]),
    ai: {
      summary: "Internal FAQ covering access requests and sharing approvals.",
      keywords: ["SSO", "access", "share"],
      classification: "Support / FAQ",
      suggestedTags: ["it-help", "sso"],
      suggestedFolder: "Customer Onboarding Pack",
      relatedDocumentIds: ["doc-policy-security", "doc-process-onboarding"],
      translationReady: true,
      ocrReady: false,
    },
  },
  {
    id: "doc-product-demo",
    name: "Product Walkthrough.mp4",
    fileType: "video",
    sizeBytes: 86_000_000,
    owner: "Casey Ng",
    createdAt: "2026-07-12T17:00:00Z",
    updatedAt: "2026-07-12T17:00:00Z",
    category: "Media",
    department: "Marketing",
    status: "draft",
    retention: "3 years",
    version: "v0.9",
    tags: ["demo", "video"],
    folderId: "f-root-creator",
    favorite: false,
    pinned: false,
    shared: false,
    archived: false,
    trashed: false,
    shareScope: "private",
    linkedModules: ["creator", "crm"],
    pages: 1,
    previewText: "Recorded product walkthrough placeholder — player wiring reserved.",
    versions: versions("doc-product-demo", [86_000_000]),
    ai: {
      summary: "Marketing demo video awaiting final edit and approval.",
      keywords: ["walkthrough", "demo"],
      classification: "Marketing / Media",
      suggestedTags: ["video", "launch"],
      suggestedFolder: "Creator Assets",
      relatedDocumentIds: ["doc-brand-guide"],
      translationReady: false,
      ocrReady: false,
    },
  },
  {
    id: "doc-call-recording",
    name: "Discovery Call Acme.mp3",
    fileType: "audio",
    sizeBytes: 12_400_000,
    owner: "Alex Morgan",
    createdAt: "2026-07-19T14:00:00Z",
    updatedAt: "2026-07-19T14:00:00Z",
    category: "Call",
    department: "Sales",
    status: "draft",
    retention: "2 years",
    version: "v1.0",
    tags: ["call", "discovery"],
    folderId: "f-root-crm",
    favorite: false,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "specific_users",
    linkedModules: ["crm"],
    pages: 1,
    previewText: "Audio capture placeholder for CRM discovery call notes.",
    versions: versions("doc-call-recording", [12_400_000]),
    ai: {
      summary: "Discovery call recording ready for AI transcription placeholder.",
      keywords: ["discovery", "requirements"],
      classification: "CRM / Audio",
      suggestedTags: ["transcript", "opportunity"],
      suggestedFolder: "CRM Records",
      relatedDocumentIds: ["doc-proposal-acme"],
      translationReady: true,
      ocrReady: false,
    },
  },
  {
    id: "doc-logo-pack",
    name: "Logo Pack.png",
    fileType: "image",
    sizeBytes: 2_200_000,
    owner: "Casey Ng",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
    category: "Asset",
    department: "Marketing",
    status: "approved",
    retention: "Indefinite",
    version: "v1.0",
    tags: ["logo", "asset"],
    folderId: "f-root-creator",
    favorite: true,
    pinned: false,
    shared: true,
    archived: false,
    trashed: false,
    shareScope: "organization",
    linkedModules: ["creator"],
    pages: 1,
    previewText: "Primary logo lockups for light and dark surfaces.",
    versions: versions("doc-logo-pack", [2_200_000]),
    ai: {
      summary: "Brand logo pack for Creator Studio and customer-facing decks.",
      keywords: ["logo", "lockup"],
      classification: "Marketing / Asset",
      suggestedTags: ["brand", "png"],
      suggestedFolder: "Creator Assets",
      relatedDocumentIds: ["doc-brand-guide"],
      translationReady: false,
      ocrReady: true,
    },
  },
  {
    id: "doc-usage-csv",
    name: "Module Usage.csv",
    fileType: "csv",
    sizeBytes: 240_000,
    owner: "Jordan Lee",
    createdAt: "2026-07-21T07:00:00Z",
    updatedAt: "2026-07-29T07:00:00Z",
    category: "Analytics",
    department: "Ops",
    status: "approved",
    retention: "3 years",
    version: "v1.0",
    tags: ["usage", "analytics"],
    folderId: "sc-ai-indexed",
    favorite: false,
    pinned: false,
    shared: false,
    archived: false,
    trashed: false,
    shareScope: "private",
    linkedModules: ["projects", "automation"],
    pages: 1,
    previewText: "module,active_users,docs_attached\ncrm,42,118\nfinance,19,86",
    versions: versions("doc-usage-csv", [240_000]),
    ai: {
      summary: "Operational CSV of module usage and document attachment density.",
      keywords: ["usage", "attachment"],
      classification: "Ops / Analytics",
      suggestedTags: ["kpi", "adoption"],
      suggestedFolder: "AI Indexed",
      relatedDocumentIds: [],
      translationReady: false,
      ocrReady: false,
    },
  },
  {
    id: "doc-archived-handbook",
    name: "Legacy Handbook.pdf",
    fileType: "pdf",
    sizeBytes: 3_100_000,
    owner: "Riley Chen",
    createdAt: "2024-11-01T09:00:00Z",
    updatedAt: "2026-01-15T09:00:00Z",
    category: "Manual",
    department: "People",
    status: "archived",
    retention: "7 years",
    version: "v8.0",
    tags: ["handbook", "legacy"],
    folderId: "f-root-hr",
    favorite: false,
    pinned: false,
    shared: false,
    archived: true,
    trashed: false,
    shareScope: "private",
    linkedModules: ["hr"],
    pages: 64,
    previewText: "Superseded employee handbook retained for audit.",
    versions: versions("doc-archived-handbook", [3_100_000]),
    ai: {
      summary: "Archived handbook superseded by wiki articles.",
      keywords: ["handbook", "legacy"],
      classification: "HR / Manual",
      suggestedTags: ["archive"],
      suggestedFolder: "People Ops",
      relatedDocumentIds: ["doc-process-onboarding"],
      duplicateOfId: "doc-process-onboarding",
      translationReady: false,
      ocrReady: true,
    },
  },
  {
    id: "doc-trash-draft",
    name: "Scratch Notes.other",
    fileType: "other",
    sizeBytes: 4_200,
    owner: "Sam Rivera",
    createdAt: "2026-07-02T09:00:00Z",
    updatedAt: "2026-07-30T09:00:00Z",
    category: "Scratch",
    department: "Sales",
    status: "draft",
    retention: "30 days",
    version: "v0.1",
    tags: ["temp"],
    folderId: "f-root-crm",
    favorite: false,
    pinned: false,
    shared: false,
    archived: false,
    trashed: true,
    shareScope: "private",
    linkedModules: [],
    pages: 1,
    previewText: "Temporary scratch file in trash — recoverable until retention lapses.",
    versions: versions("doc-trash-draft", [4_200]),
    ai: {
      summary: "Trashed scratch artifact pending purge.",
      keywords: ["temp"],
      classification: "Scratch",
      suggestedTags: ["cleanup"],
      suggestedFolder: "Trash",
      relatedDocumentIds: [],
      translationReady: false,
      ocrReady: false,
    },
  },
];

export const KNOWLEDGE_ARTICLES: readonly KnowledgeArticle[] = [
  {
    id: "kb-article-os",
    title: "How AGXORA Knowledge Hub Connects Modules",
    kind: "article",
    summary: "Every CRM, Finance, Automation, and Creator record can attach hub documents.",
    owner: "Alex Morgan",
    updatedAt: "2026-07-28T10:00:00Z",
    tags: ["architecture", "hub"],
    status: "approved",
  },
  {
    id: "kb-policy-sharing",
    title: "External Sharing Policy",
    kind: "policy",
    summary: "Public links are placeholders until security review clears them.",
    owner: "Riley Chen",
    updatedAt: "2026-07-20T10:00:00Z",
    tags: ["sharing", "security"],
    status: "approved",
  },
  {
    id: "kb-process-approval",
    title: "Document Approval Process",
    kind: "process",
    summary: "Draft → In Review → Approved / Rejected, with Automation hooks reserved.",
    owner: "Jordan Lee",
    updatedAt: "2026-07-25T10:00:00Z",
    tags: ["approval", "automation"],
    status: "approved",
  },
  {
    id: "kb-manual-upload",
    title: "Bulk Upload Manual",
    kind: "manual",
    summary: "Drag & drop upload is a UX placeholder awaiting storage API.",
    owner: "Casey Ng",
    updatedAt: "2026-07-18T10:00:00Z",
    tags: ["upload", "manual"],
    status: "in_review",
  },
  {
    id: "kb-faq-search",
    title: "AI Search FAQ",
    kind: "faq",
    summary: "AI search is architecture-only — global filters work locally on mock data.",
    owner: "Sam Rivera",
    updatedAt: "2026-07-27T10:00:00Z",
    tags: ["ai", "search"],
    status: "approved",
  },
  {
    id: "kb-wiki-taxonomy",
    title: "Taxonomy & Smart Collections",
    kind: "wiki",
    summary: "Folders, collections, tags, and smart collections form the knowledge graph skeleton.",
    owner: "Alex Morgan",
    updatedAt: "2026-07-29T10:00:00Z",
    tags: ["taxonomy", "wiki"],
    status: "draft",
  },
];

export const DOCUMENT_ACTIVITY: readonly DocumentActivity[] = [
  {
    id: "act-1",
    kind: "upload",
    title: "Recent Upload",
    detail: "Q2 Invoice Export.xlsx uploaded to Finance / Invoices",
    actor: "Sam Rivera",
    at: "2026-07-29T11:10:00Z",
    documentId: "doc-invoice-pack",
  },
  {
    id: "act-2",
    kind: "change",
    title: "Recent Change",
    detail: "Acme MSA moved to In Review",
    actor: "Alex Morgan",
    at: "2026-07-27T09:30:00Z",
    documentId: "doc-contract-acme",
  },
  {
    id: "act-3",
    kind: "view",
    title: "Recent View",
    detail: "Brand System Guide.pdf opened 14 times today",
    actor: "Casey Ng",
    at: "2026-07-30T08:40:00Z",
    documentId: "doc-brand-guide",
  },
  {
    id: "act-4",
    kind: "share",
    title: "Recent Share",
    detail: "Access FAQ shared organization-wide",
    actor: "Riley Chen",
    at: "2026-07-28T08:10:00Z",
    documentId: "doc-faq-access",
  },
  {
    id: "act-5",
    kind: "audit",
    title: "Audit History",
    detail: "Retention policy evaluated for Legacy Handbook.pdf",
    actor: "System",
    at: "2026-07-29T02:00:00Z",
    documentId: "doc-archived-handbook",
  },
  {
    id: "act-6",
    kind: "change",
    title: "Version Restored",
    detail: "VAT Memo DE.md compared against v1.0 (placeholder)",
    actor: "Jordan Lee",
    at: "2026-07-20T16:40:00Z",
    documentId: "doc-tax-memo",
  },
];
