import type { BusinessTemplate } from "./types";

function template(
  partial: Omit<BusinessTemplate, "version"> & { version?: string },
): BusinessTemplate {
  return {
    version: partial.version ?? "1.0.0",
    ...partial,
  };
}

export const BUSINESS_TEMPLATES: readonly BusinessTemplate[] = [
  template({
    id: "tpl.hotel.core",
    businessType: "hotel",
    name: "Hotel Operations",
    summary: "Guest journey, rooms, housekeeping, and revenue management",
    defaultModules: ["crm", "operations", "scheduling", "finance", "analytics"],
    defaultAgents: ["operations", "revenue", "customer", "scheduling"],
    defaultRoles: ["owner", "general_manager", "front_desk", "housekeeping", "viewer"],
    starterWorkflows: ["check_in", "housekeeping_cycle", "rate_update"],
    knowledgeSeeds: [
      "Property profile and room inventory",
      "Guest service standards",
      "Seasonal occupancy patterns",
    ],
    aiFocus: ["occupancy", "guest satisfaction", "upsell opportunities"],
  }),
  template({
    id: "tpl.restaurant.core",
    businessType: "restaurant",
    name: "Restaurant Operations",
    summary: "Reservations, kitchen flow, menu performance, and service",
    defaultModules: ["crm", "operations", "inventory", "scheduling", "analytics"],
    defaultAgents: ["operations", "customer", "insights", "scheduling"],
    defaultRoles: ["owner", "manager", "chef", "server", "viewer"],
    starterWorkflows: ["reservation_confirm", "prep_list", "closing_report"],
    knowledgeSeeds: [
      "Menu catalog and allergens",
      "Service style and hours",
      "Supplier preferences",
    ],
    aiFocus: ["covers", "ticket times", "menu mix"],
  }),
  template({
    id: "tpl.retail.core",
    businessType: "retail",
    name: "Retail Commerce",
    summary: "Assortment, stock, customers, and store performance",
    defaultModules: ["crm", "inventory", "finance", "analytics", "support"],
    defaultAgents: ["revenue", "customer", "insights", "operations"],
    defaultRoles: ["owner", "store_manager", "associate", "viewer"],
    starterWorkflows: ["restock_alert", "promo_launch", "daily_sales_close"],
    knowledgeSeeds: [
      "Product catalog",
      "Pricing rules",
      "Customer segments",
    ],
    aiFocus: ["sell-through", "basket size", "stockouts"],
  }),
  template({
    id: "tpl.manufacturing.core",
    businessType: "manufacturing",
    name: "Manufacturing Ops",
    summary: "Production, quality, materials, and plant throughput",
    defaultModules: ["operations", "inventory", "compliance", "analytics", "automation"],
    defaultAgents: ["operations", "compliance", "insights"],
    defaultRoles: ["owner", "plant_manager", "supervisor", "operator", "viewer"],
    starterWorkflows: ["work_order", "quality_check", "maintenance_ticket"],
    knowledgeSeeds: [
      "Bill of materials",
      "Line capacities",
      "Quality thresholds",
    ],
    aiFocus: ["yield", "downtime", "scrap rate"],
  }),
  template({
    id: "tpl.laundry.core",
    businessType: "laundry",
    name: "Laundry & Textile Care",
    summary: "Orders, routes, plant capacity, and customer delivery",
    defaultModules: ["crm", "operations", "scheduling", "logistics", "analytics"],
    defaultAgents: ["operations", "scheduling", "customer"],
    defaultRoles: ["owner", "dispatcher", "plant_lead", "driver", "viewer"],
    starterWorkflows: ["pickup_route", "wash_cycle", "delivery_confirm"],
    knowledgeSeeds: [
      "Service catalog and turnaround SLAs",
      "Route zones",
      "Plant capacity windows",
    ],
    aiFocus: ["route density", "on-time delivery", "plant utilization"],
  }),
  template({
    id: "tpl.medical.core",
    businessType: "medical",
    name: "Medical Practice",
    summary: "Patients, appointments, care teams, and compliance",
    defaultModules: ["crm", "scheduling", "documents", "compliance", "analytics"],
    defaultAgents: ["scheduling", "customer", "compliance", "insights"],
    defaultRoles: ["owner", "practitioner", "front_office", "nurse", "viewer"],
    starterWorkflows: ["appointment_book", "intake_forms", "follow_up"],
    knowledgeSeeds: [
      "Clinic hours and specialties",
      "Care protocols",
      "Insurance preferences",
    ],
    aiFocus: ["no-show risk", "panel load", "follow-up adherence"],
  }),
  template({
    id: "tpl.logistics.core",
    businessType: "logistics",
    name: "Logistics & Fulfillment",
    summary: "Fleet, warehouses, routes, and delivery performance",
    defaultModules: ["operations", "inventory", "scheduling", "analytics", "automation"],
    defaultAgents: ["operations", "scheduling", "insights"],
    defaultRoles: ["owner", "dispatcher", "warehouse_lead", "driver", "viewer"],
    starterWorkflows: ["dispatch_plan", "warehouse_pick", "pod_capture"],
    knowledgeSeeds: [
      "Fleet profile",
      "Warehouse layout",
      "SLA commitments",
    ],
    aiFocus: ["on-time rate", "cost per mile", "dock utilization"],
  }),
  template({
    id: "tpl.real_estate.core",
    businessType: "real_estate",
    name: "Real Estate",
    summary: "Listings, clients, showings, and deal pipeline",
    defaultModules: ["crm", "documents", "scheduling", "analytics", "finance"],
    defaultAgents: ["customer", "revenue", "scheduling", "insights"],
    defaultRoles: ["owner", "broker", "agent", "assistant", "viewer"],
    starterWorkflows: ["listing_publish", "showing_schedule", "offer_track"],
    knowledgeSeeds: [
      "Market areas",
      "Listing playbooks",
      "Client preferences",
    ],
    aiFocus: ["pipeline velocity", "showing conversion", "days on market"],
  }),
  template({
    id: "tpl.saas.core",
    businessType: "saas",
    name: "SaaS Company",
    summary: "Subscriptions, usage, expansion, and customer health",
    defaultModules: ["crm", "analytics", "support", "finance", "automation"],
    defaultAgents: ["customer", "revenue", "insights", "operations"],
    defaultRoles: ["owner", "cs_lead", "ae", "support", "viewer"],
    starterWorkflows: ["trial_convert", "churn_risk", "expansion_play"],
    knowledgeSeeds: [
      "Product packaging",
      "Success playbooks",
      "Pricing tiers",
    ],
    aiFocus: ["NRR", "activation", "churn risk"],
  }),
  template({
    id: "tpl.agency.core",
    businessType: "agency",
    name: "Agency",
    summary: "Clients, retainers, campaigns, and delivery capacity",
    defaultModules: ["crm", "operations", "documents", "analytics", "finance"],
    defaultAgents: ["customer", "operations", "insights", "revenue"],
    defaultRoles: ["owner", "account_lead", "strategist", "creator", "viewer"],
    starterWorkflows: ["brief_intake", "campaign_launch", "retainer_renewal"],
    knowledgeSeeds: [
      "Service offerings",
      "Client brand guidelines",
      "Delivery SLAs",
    ],
    aiFocus: ["utilization", "retainer health", "campaign ROI"],
  }),
  template({
    id: "tpl.legal.core",
    businessType: "legal",
    name: "Legal Practice",
    summary: "Matters, clients, time, billing, and compliance",
    defaultModules: ["crm", "documents", "finance", "compliance", "analytics"],
    defaultAgents: ["compliance", "customer", "insights", "revenue"],
    defaultRoles: ["owner", "partner", "associate", "paralegal", "viewer"],
    starterWorkflows: ["matter_open", "time_entry", "billing_cycle"],
    knowledgeSeeds: [
      "Practice areas",
      "Engagement letter standards",
      "Billing rules",
    ],
    aiFocus: ["realization", "matter aging", "conflict checks"],
  }),
] as const;
