/**
 * BusinessTemplates — industry operating packs for the Universal AI OS.
 * Easily extendable: add a template object, register via BusinessRegistry.
 */

import type { BusinessType } from "./BusinessType";
import type {
  BusinessTemplate,
  TemplateAgentKey,
  TemplateModuleKey,
} from "./templates/types";

function tpl(input: {
  id: string;
  businessType: BusinessType;
  name: string;
  summary: string;
  defaultModules: readonly TemplateModuleKey[];
  defaultAgents: readonly TemplateAgentKey[];
  defaultRoles: readonly string[];
  starterWorkflows: readonly string[];
  knowledgeSeeds: readonly string[];
  aiFocus: readonly string[];
  version?: string;
}): BusinessTemplate {
  return {
    version: input.version ?? "1.0.0",
    id: input.id,
    businessType: input.businessType,
    name: input.name,
    summary: input.summary,
    defaultModules: input.defaultModules,
    defaultAgents: input.defaultAgents,
    defaultRoles: input.defaultRoles,
    starterWorkflows: input.starterWorkflows,
    knowledgeSeeds: input.knowledgeSeeds,
    aiFocus: input.aiFocus,
  };
}

export const BUSINESS_TEMPLATES: readonly BusinessTemplate[] = [
  tpl({
    id: "tpl.hotel.core",
    businessType: "hotel",
    name: "Hotel Operations",
    summary: "Guest journey, rooms, housekeeping, and revenue management",
    defaultModules: ["crm", "operations", "scheduling", "finance", "analytics"],
    defaultAgents: ["operations", "revenue", "customer", "scheduling"],
    defaultRoles: ["owner", "general_manager", "front_desk", "housekeeping", "viewer"],
    starterWorkflows: ["check_in", "housekeeping_cycle", "rate_update"],
    knowledgeSeeds: ["Property profile and room inventory", "Guest service standards", "Seasonal occupancy patterns"],
    aiFocus: ["occupancy", "ADR", "RevPAR", "housekeeping"],
  }),
  tpl({
    id: "tpl.restaurant.core",
    businessType: "restaurant",
    name: "Restaurant Operations",
    summary: "Reservations, kitchen flow, menu performance, and service",
    defaultModules: ["crm", "operations", "inventory", "scheduling", "analytics"],
    defaultAgents: ["operations", "customer", "insights", "scheduling"],
    defaultRoles: ["owner", "manager", "chef", "server", "viewer"],
    starterWorkflows: ["reservation_confirm", "prep_list", "closing_report"],
    knowledgeSeeds: ["Menu catalog and allergens", "Service style and hours", "Supplier preferences"],
    aiFocus: ["inventory", "food cost", "menu optimization", "staff scheduling"],
  }),
  tpl({
    id: "tpl.laundry.core",
    businessType: "laundry",
    name: "Laundry & Textile Care",
    summary: "Orders, routes, plant capacity, and customer delivery",
    defaultModules: ["crm", "operations", "scheduling", "logistics", "analytics"],
    defaultAgents: ["operations", "scheduling", "customer"],
    defaultRoles: ["owner", "dispatcher", "plant_lead", "driver", "viewer"],
    starterWorkflows: ["pickup_route", "wash_cycle", "delivery_confirm"],
    knowledgeSeeds: ["Service catalog and turnaround SLAs", "Route zones", "Plant capacity windows"],
    aiFocus: ["machines", "capacity", "pickup routes", "chemical usage"],
  }),
  tpl({
    id: "tpl.cleaning.core",
    businessType: "cleaning",
    name: "Cleaning Company",
    summary: "Crews, sites, quality checks, and recurring contracts",
    defaultModules: ["crm", "operations", "scheduling", "analytics", "support"],
    defaultAgents: ["operations", "scheduling", "customer", "insights"],
    defaultRoles: ["owner", "supervisor", "cleaner", "viewer"],
    starterWorkflows: ["job_dispatch", "quality_check", "supply_restock"],
    knowledgeSeeds: ["Service checklist library", "Client site notes", "Crew skill matrix"],
    aiFocus: ["routes", "crew scheduling", "quality checks", "supplies"],
  }),
  tpl({
    id: "tpl.medical.core",
    businessType: "medical",
    name: "Medical Practice",
    summary: "Patients, appointments, care teams, and compliance",
    defaultModules: ["crm", "scheduling", "documents", "compliance", "analytics"],
    defaultAgents: ["scheduling", "customer", "compliance", "insights"],
    defaultRoles: ["owner", "practitioner", "front_office", "nurse", "viewer"],
    starterWorkflows: ["appointment_book", "intake_forms", "follow_up"],
    knowledgeSeeds: ["Clinic hours and specialties", "Care protocols", "Insurance preferences"],
    aiFocus: ["appointments", "patients", "care protocols", "billing"],
  }),
  tpl({
    id: "tpl.healthcare.core",
    businessType: "healthcare",
    name: "Healthcare Network",
    summary: "Facilities, care pathways, capacity, and outcomes",
    defaultModules: ["operations", "scheduling", "compliance", "analytics", "documents"],
    defaultAgents: ["operations", "compliance", "insights", "scheduling"],
    defaultRoles: ["owner", "admin", "clinician", "viewer"],
    starterWorkflows: ["admission", "care_pathway", "discharge"],
    knowledgeSeeds: ["Facility network", "Care pathways", "Compliance policies"],
    aiFocus: ["care pathways", "capacity", "compliance", "outcomes"],
  }),
  tpl({
    id: "tpl.legal.core",
    businessType: "legal",
    name: "Law Firm",
    summary: "Matters, clients, time, billing, and deadlines",
    defaultModules: ["crm", "documents", "finance", "compliance", "analytics"],
    defaultAgents: ["compliance", "customer", "insights", "revenue"],
    defaultRoles: ["owner", "partner", "associate", "paralegal", "viewer"],
    starterWorkflows: ["matter_open", "time_entry", "billing_cycle"],
    knowledgeSeeds: ["Practice areas", "Engagement letter standards", "Billing rules"],
    aiFocus: ["cases", "clients", "deadlines", "billing"],
  }),
  tpl({
    id: "tpl.retail.core",
    businessType: "retail",
    name: "Retail Commerce",
    summary: "Assortment, stock, customers, and store performance",
    defaultModules: ["crm", "inventory", "finance", "analytics", "support"],
    defaultAgents: ["revenue", "customer", "insights", "operations"],
    defaultRoles: ["owner", "store_manager", "associate", "viewer"],
    starterWorkflows: ["restock_alert", "promo_launch", "daily_sales_close"],
    knowledgeSeeds: ["Product catalog", "Pricing rules", "Customer segments"],
    aiFocus: ["inventory", "assortment", "pricing", "customers"],
  }),
  tpl({
    id: "tpl.manufacturing.core",
    businessType: "manufacturing",
    name: "Manufacturing Ops",
    summary: "Production, quality, materials, and plant throughput",
    defaultModules: ["operations", "inventory", "compliance", "analytics", "automation"],
    defaultAgents: ["operations", "compliance", "insights"],
    defaultRoles: ["owner", "plant_manager", "supervisor", "operator", "viewer"],
    starterWorkflows: ["work_order", "quality_check", "maintenance_ticket"],
    knowledgeSeeds: ["Bill of materials", "Line capacities", "Quality thresholds"],
    aiFocus: ["production", "quality", "inventory", "maintenance"],
  }),
  tpl({
    id: "tpl.construction.core",
    businessType: "construction",
    name: "Construction",
    summary: "Jobsites, crews, materials, safety, and delivery",
    defaultModules: ["operations", "crm", "documents", "finance", "analytics"],
    defaultAgents: ["operations", "compliance", "insights", "scheduling"],
    defaultRoles: ["owner", "pm", "superintendent", "viewer"],
    starterWorkflows: ["job_kickoff", "daily_report", "change_order"],
    knowledgeSeeds: ["Project playbooks", "Safety standards", "Vendor list"],
    aiFocus: ["jobsites", "crews", "materials", "safety"],
  }),
  tpl({
    id: "tpl.consulting.core",
    businessType: "consulting",
    name: "Consulting Firm",
    summary: "Engagements, utilization, deliverables, and accounts",
    defaultModules: ["crm", "operations", "documents", "finance", "analytics"],
    defaultAgents: ["customer", "operations", "insights", "revenue"],
    defaultRoles: ["owner", "partner", "consultant", "viewer"],
    starterWorkflows: ["engagement_start", "status_report", "closeout"],
    knowledgeSeeds: ["Service offerings", "Delivery methodology", "Case library"],
    aiFocus: ["engagements", "utilization", "deliverables", "accounts"],
  }),
  tpl({
    id: "tpl.agency.core",
    businessType: "agency",
    name: "Marketing Agency",
    summary: "Clients, retainers, campaigns, and delivery capacity",
    defaultModules: ["crm", "operations", "documents", "analytics", "finance"],
    defaultAgents: ["customer", "operations", "insights", "revenue"],
    defaultRoles: ["owner", "account_lead", "strategist", "creator", "viewer"],
    starterWorkflows: ["brief_intake", "campaign_launch", "retainer_renewal"],
    knowledgeSeeds: ["Service offerings", "Client brand guidelines", "Delivery SLAs"],
    aiFocus: ["clients", "campaigns", "retainers", "creative capacity"],
  }),
  tpl({
    id: "tpl.real_estate.core",
    businessType: "real_estate",
    name: "Real Estate",
    summary: "Listings, clients, showings, and deal pipeline",
    defaultModules: ["crm", "documents", "scheduling", "analytics", "finance"],
    defaultAgents: ["customer", "revenue", "scheduling", "insights"],
    defaultRoles: ["owner", "broker", "agent", "assistant", "viewer"],
    starterWorkflows: ["listing_publish", "showing_schedule", "offer_track"],
    knowledgeSeeds: ["Market areas", "Listing playbooks", "Client preferences"],
    aiFocus: ["listings", "clients", "showings", "pipeline"],
  }),
  tpl({
    id: "tpl.education.core",
    businessType: "education",
    name: "Education",
    summary: "Programs, enrollment, faculty load, and outcomes",
    defaultModules: ["crm", "scheduling", "documents", "analytics", "support"],
    defaultAgents: ["customer", "scheduling", "insights", "operations"],
    defaultRoles: ["owner", "dean", "instructor", "advisor", "viewer"],
    starterWorkflows: ["enrollment", "term_planning", "outcome_review"],
    knowledgeSeeds: ["Program catalog", "Academic calendar", "Outcome metrics"],
    aiFocus: ["enrollment", "curriculum", "outcomes", "faculty load"],
  }),
  tpl({
    id: "tpl.logistics.core",
    businessType: "logistics",
    name: "Logistics & Fulfillment",
    summary: "Fleet, warehouses, routes, and delivery performance",
    defaultModules: ["operations", "inventory", "scheduling", "analytics", "automation"],
    defaultAgents: ["operations", "scheduling", "insights"],
    defaultRoles: ["owner", "dispatcher", "warehouse_lead", "driver", "viewer"],
    starterWorkflows: ["dispatch_plan", "warehouse_pick", "pod_capture"],
    knowledgeSeeds: ["Fleet profile", "Warehouse layout", "SLA commitments"],
    aiFocus: ["fleet", "routes", "warehouses", "SLAs"],
  }),
  tpl({
    id: "tpl.warehouse.core",
    businessType: "warehouse",
    name: "Warehouse",
    summary: "Inbound, slotting, picks, packing, and inventory turns",
    defaultModules: ["inventory", "operations", "analytics", "automation", "logistics"],
    defaultAgents: ["operations", "insights", "scheduling"],
    defaultRoles: ["owner", "warehouse_manager", "picker", "viewer"],
    starterWorkflows: ["inbound_receive", "wave_pick", "cycle_count"],
    knowledgeSeeds: ["Slotting map", "SKU velocity classes", "Labor standards"],
    aiFocus: ["slotting", "picks", "inventory", "labor"],
  }),
  tpl({
    id: "tpl.automotive.core",
    businessType: "automotive",
    name: "Car Dealer",
    summary: "Sales, service bays, parts, and F&I operations",
    defaultModules: ["crm", "inventory", "operations", "finance", "analytics"],
    defaultAgents: ["revenue", "customer", "operations", "insights"],
    defaultRoles: ["owner", "sales_manager", "service_advisor", "viewer"],
    starterWorkflows: ["lead_to_sale", "service_ro", "aged_unit_review"],
    knowledgeSeeds: ["Inventory policy", "Service menu", "F&I products"],
    aiFocus: ["inventory", "service bays", "F&I", "customers"],
  }),
  tpl({
    id: "tpl.beauty.core",
    businessType: "beauty",
    name: "Beauty Salon",
    summary: "Appointments, stylists, retail attach, and memberships",
    defaultModules: ["crm", "scheduling", "inventory", "analytics", "finance"],
    defaultAgents: ["scheduling", "customer", "revenue", "insights"],
    defaultRoles: ["owner", "stylist", "front_desk", "viewer"],
    starterWorkflows: ["booking", "service_complete", "rebook_prompt"],
    knowledgeSeeds: ["Service menu", "Stylist skills", "Retail catalog"],
    aiFocus: ["appointments", "stylists", "retail attach", "memberships"],
  }),
  tpl({
    id: "tpl.fitness.core",
    businessType: "fitness",
    name: "Gym / Fitness",
    summary: "Memberships, classes, trainers, and retention",
    defaultModules: ["crm", "scheduling", "analytics", "finance", "support"],
    defaultAgents: ["customer", "scheduling", "insights", "revenue"],
    defaultRoles: ["owner", "trainer", "front_desk", "viewer"],
    starterWorkflows: ["member_onboard", "class_schedule", "churn_save"],
    knowledgeSeeds: ["Membership plans", "Class catalog", "Trainer roster"],
    aiFocus: ["memberships", "classes", "trainers", "retention"],
  }),
  tpl({
    id: "tpl.freelancer.core",
    businessType: "freelancer",
    name: "Freelancer",
    summary: "Pipeline, delivery, cashflow, and positioning",
    defaultModules: ["crm", "finance", "documents", "analytics", "automation"],
    defaultAgents: ["revenue", "customer", "insights", "operations"],
    defaultRoles: ["owner", "viewer"],
    starterWorkflows: ["proposal", "delivery_milestone", "invoice"],
    knowledgeSeeds: ["Service offers", "Rate card", "Portfolio highlights"],
    aiFocus: ["pipeline", "delivery", "cashflow", "positioning"],
  }),
  tpl({
    id: "tpl.saas.core",
    businessType: "saas",
    name: "Software Company",
    summary: "Subscriptions, usage, expansion, and customer health",
    defaultModules: ["crm", "analytics", "support", "finance", "automation"],
    defaultAgents: ["customer", "revenue", "insights", "operations"],
    defaultRoles: ["owner", "cs_lead", "ae", "support", "viewer"],
    starterWorkflows: ["trial_convert", "churn_risk", "expansion_play"],
    knowledgeSeeds: ["Product packaging", "Success playbooks", "Pricing tiers"],
    aiFocus: ["subscriptions", "usage", "churn", "expansion"],
  }),
  tpl({
    id: "tpl.technology.core",
    businessType: "technology",
    name: "Technology Company",
    summary: "Product, reliability, roadmap, and customers",
    defaultModules: ["operations", "analytics", "support", "crm", "documents"],
    defaultAgents: ["operations", "insights", "customer", "compliance"],
    defaultRoles: ["owner", "eng_lead", "product", "viewer"],
    starterWorkflows: ["incident", "release", "roadmap_review"],
    knowledgeSeeds: ["Product catalog", "SLO policy", "Support runbooks"],
    aiFocus: ["product", "reliability", "roadmap", "customers"],
  }),
  tpl({
    id: "tpl.accounting.core",
    businessType: "accounting",
    name: "Accounting Firm",
    summary: "Clients, books, filings, and advisory capacity",
    defaultModules: ["crm", "finance", "documents", "compliance", "analytics"],
    defaultAgents: ["compliance", "customer", "revenue", "insights"],
    defaultRoles: ["owner", "manager", "accountant", "viewer"],
    starterWorkflows: ["client_onboard", "month_close", "tax_filing"],
    knowledgeSeeds: ["Service catalog", "Filing calendar", "Engagement letters"],
    aiFocus: ["clients", "filings", "books", "deadlines"],
  }),
  tpl({
    id: "tpl.insurance.core",
    businessType: "insurance",
    name: "Insurance",
    summary: "Policies, claims, underwriting, and retention",
    defaultModules: ["crm", "operations", "compliance", "analytics", "finance"],
    defaultAgents: ["compliance", "customer", "insights", "operations"],
    defaultRoles: ["owner", "underwriter", "claims", "viewer"],
    starterWorkflows: ["quote", "bind", "claim_intake"],
    knowledgeSeeds: ["Product shelves", "Underwriting guidelines", "Claims SLAs"],
    aiFocus: ["policies", "claims", "underwriting", "retention"],
  }),
  tpl({
    id: "tpl.financial_services.core",
    businessType: "financial_services",
    name: "Financial Services",
    summary: "Clients, portfolios, planning, and compliance",
    defaultModules: ["crm", "finance", "compliance", "documents", "analytics"],
    defaultAgents: ["compliance", "customer", "insights", "revenue"],
    defaultRoles: ["owner", "advisor", "ops", "viewer"],
    starterWorkflows: ["kyc", "plan_review", "rebalance"],
    knowledgeSeeds: ["Advice frameworks", "Product shelf", "Compliance checklist"],
    aiFocus: ["clients", "portfolios", "compliance", "planning"],
  }),
  tpl({
    id: "tpl.finance.core",
    businessType: "finance",
    name: "Finance Institution",
    summary: "Portfolios, risk, liquidity, and compliance",
    defaultModules: ["finance", "analytics", "compliance", "operations", "documents"],
    defaultAgents: ["compliance", "insights", "operations", "revenue"],
    defaultRoles: ["owner", "risk", "ops", "viewer"],
    starterWorkflows: ["risk_review", "liquidity_check", "audit_prep"],
    knowledgeSeeds: ["Risk appetite", "Product book", "Regulatory calendar"],
    aiFocus: ["portfolios", "risk", "liquidity", "compliance"],
  }),
  tpl({
    id: "tpl.ecommerce.core",
    businessType: "ecommerce",
    name: "E-Commerce",
    summary: "Catalog, conversion, fulfillment, and LTV",
    defaultModules: ["crm", "inventory", "analytics", "logistics", "finance"],
    defaultAgents: ["revenue", "customer", "operations", "insights"],
    defaultRoles: ["owner", "merchandiser", "ops", "viewer"],
    starterWorkflows: ["campaign_drop", "fulfillment", "returns"],
    knowledgeSeeds: ["Catalog taxonomy", "Shipping SLAs", "Return policy"],
    aiFocus: ["catalog", "conversion", "fulfillment", "LTV"],
  }),
  tpl({
    id: "tpl.government.core",
    businessType: "government",
    name: "Government",
    summary: "Programs, service levels, compliance, and constituents",
    defaultModules: ["operations", "documents", "compliance", "analytics", "support"],
    defaultAgents: ["operations", "compliance", "insights", "customer"],
    defaultRoles: ["owner", "program_lead", "officer", "viewer"],
    starterWorkflows: ["case_open", "service_request", "reporting_cycle"],
    knowledgeSeeds: ["Program catalog", "SLA matrix", "Policy library"],
    aiFocus: ["programs", "service levels", "compliance", "constituents"],
  }),
  tpl({
    id: "tpl.nonprofit.core",
    businessType: "nonprofit",
    name: "Non-Profit",
    summary: "Donors, programs, impact, and fundraising",
    defaultModules: ["crm", "finance", "documents", "analytics", "support"],
    defaultAgents: ["customer", "insights", "revenue", "operations"],
    defaultRoles: ["owner", "program_lead", "fundraiser", "viewer"],
    starterWorkflows: ["campaign", "grant_report", "impact_update"],
    knowledgeSeeds: ["Mission statement", "Program outcomes", "Donor segments"],
    aiFocus: ["donors", "programs", "impact", "fundraising"],
  }),
  tpl({
    id: "tpl.agriculture.core",
    businessType: "agriculture",
    name: "Agriculture",
    summary: "Yield, inputs, equipment, and supply chain",
    defaultModules: ["operations", "inventory", "analytics", "finance", "logistics"],
    defaultAgents: ["operations", "insights", "compliance"],
    defaultRoles: ["owner", "farm_manager", "operator", "viewer"],
    starterWorkflows: ["season_plan", "harvest", "input_order"],
    knowledgeSeeds: ["Field map", "Crop plan", "Equipment roster"],
    aiFocus: ["yield", "inputs", "equipment", "supply chain"],
  }),
  tpl({
    id: "tpl.transport.core",
    businessType: "transport",
    name: "Transport",
    summary: "Fleet, schedules, maintenance, and safety",
    defaultModules: ["operations", "scheduling", "analytics", "compliance", "logistics"],
    defaultAgents: ["operations", "scheduling", "compliance", "insights"],
    defaultRoles: ["owner", "dispatcher", "driver", "viewer"],
    starterWorkflows: ["trip_plan", "maintenance", "incident"],
    knowledgeSeeds: ["Fleet roster", "Route book", "Safety policy"],
    aiFocus: ["fleet", "schedules", "maintenance", "safety"],
  }),
] as const;

export function listBusinessTemplates(): readonly BusinessTemplate[] {
  return BUSINESS_TEMPLATES;
}

export function getTemplatesForType(
  type: BusinessType,
): readonly BusinessTemplate[] {
  return BUSINESS_TEMPLATES.filter((item) => item.businessType === type);
}
