/**
 * Business Catalog — recognition metadata for every supported business type.
 * Used by the Business Brain to reason differently per industry.
 */

import type { BusinessSize, BusinessType } from "./BusinessType";
import { BUSINESS_TYPE_META, getBusinessTypeMeta } from "./BusinessType";
import {
  getSpecializedMetrics,
  type MetricDefinition,
} from "./BusinessMetrics";

export interface BusinessCatalogEntry {
  readonly type: BusinessType;
  readonly label: string;
  readonly industry: string;
  readonly industryFamily: string;
  readonly description: string;
  readonly defaultSize: BusinessSize;
  readonly defaultCurrency: string;
  readonly defaultDepartments: readonly string[];
  readonly typicalServices: readonly string[];
  readonly typicalProducts: readonly string[];
  readonly typicalCustomers: readonly string[];
  readonly typicalSuppliers: readonly string[];
  readonly typicalLocations: readonly string[];
  readonly defaultGoals: readonly string[];
  readonly defaultKpis: readonly string[];
  readonly painPoints: readonly string[];
  /** Domains the AI should reason about for this business. */
  readonly reasoningDomains: readonly string[];
  readonly specializedMetrics: readonly MetricDefinition[];
}

function entry(
  type: BusinessType,
  partial: Omit<
    BusinessCatalogEntry,
    "type" | "label" | "industryFamily" | "description" | "specializedMetrics" | "industry"
  > & { industry?: string },
): BusinessCatalogEntry {
  const meta = getBusinessTypeMeta(type);
  return {
    type,
    label: meta.label,
    industry: partial.industry ?? meta.label,
    industryFamily: meta.industryFamily,
    description: meta.description,
    specializedMetrics: getSpecializedMetrics(type),
    ...partial,
  };
}

export const BUSINESS_CATALOG: readonly BusinessCatalogEntry[] = [
  entry("hotel", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Front Desk", "Housekeeping", "Food & Beverage", "Revenue", "Maintenance"],
    typicalServices: ["Rooms", "Events", "Spa", "Dining"],
    typicalProducts: ["Room nights", "Packages"],
    typicalCustomers: ["Leisure guests", "Corporate travelers", "Groups"],
    typicalSuppliers: ["Linen", "Food vendors", "Amenities"],
    typicalLocations: ["Property", "Outlets"],
    defaultGoals: ["Raise occupancy", "Improve guest satisfaction", "Grow RevPAR"],
    defaultKpis: ["Occupancy", "ADR", "RevPAR"],
    painPoints: ["Seasonality", "Labor coverage", "Channel mix"],
    reasoningDomains: ["occupancy", "ADR", "RevPAR", "housekeeping", "guest experience"],
  }),
  entry("restaurant", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Kitchen", "Floor", "Bar", "Management"],
    typicalServices: ["Dine-in", "Takeout", "Catering"],
    typicalProducts: ["Menu items", "Beverages"],
    typicalCustomers: ["Diners", "Delivery guests"],
    typicalSuppliers: ["Food distributors", "Beverage vendors"],
    typicalLocations: ["Dining room", "Kitchen"],
    defaultGoals: ["Lower food cost", "Speed ticket times", "Grow covers"],
    defaultKpis: ["Food cost", "Covers", "Ticket time"],
    painPoints: ["Waste", "Staffing", "Menu mix"],
    reasoningDomains: ["inventory", "food cost", "menu optimization", "staff scheduling"],
  }),
  entry("laundry", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Plant", "Routes", "Customer Care"],
    typicalServices: ["Wash & fold", "Commercial linen", "Pickup / delivery"],
    typicalProducts: ["Laundry cycles", "Route stops"],
    typicalCustomers: ["Households", "Hotels", "Clinics"],
    typicalSuppliers: ["Chemicals", "Machine parts", "Packaging"],
    typicalLocations: ["Plant", "Route zones"],
    defaultGoals: ["Maximize plant capacity", "Improve on-time delivery"],
    defaultKpis: ["Utilization", "On-time delivery", "Chemical usage"],
    painPoints: ["Route density", "Machine downtime", "Chemical cost"],
    reasoningDomains: ["machines", "capacity", "pickup routes", "chemical usage"],
  }),
  entry("cleaning", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Operations", "Quality", "Sales"],
    typicalServices: ["Commercial cleaning", "Residential cleaning"],
    typicalProducts: ["Cleaning jobs", "Maintenance contracts"],
    typicalCustomers: ["Offices", "Homes", "Facilities"],
    typicalSuppliers: ["Supplies", "Equipment"],
    typicalLocations: ["Client sites"],
    defaultGoals: ["Reduce rework", "Improve route efficiency"],
    defaultKpis: ["Jobs completed", "Rework rate"],
    painPoints: ["No-shows", "Supply waste", "Quality variance"],
    reasoningDomains: ["routes", "crew scheduling", "quality checks", "supplies"],
  }),
  entry("medical", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Front Office", "Clinical", "Billing"],
    typicalServices: ["Consultations", "Procedures", "Follow-ups"],
    typicalProducts: ["Appointments", "Care plans"],
    typicalCustomers: ["Patients"],
    typicalSuppliers: ["Labs", "Pharma", "Equipment"],
    typicalLocations: ["Clinic"],
    defaultGoals: ["Reduce no-shows", "Balance panel load"],
    defaultKpis: ["No-show rate", "Panel load"],
    painPoints: ["Scheduling gaps", "Documentation load"],
    reasoningDomains: ["appointments", "patients", "care protocols", "billing"],
  }),
  entry("healthcare", {
    defaultSize: "large",
    defaultCurrency: "USD",
    defaultDepartments: ["Clinical", "Nursing", "Admin", "Revenue Cycle"],
    typicalServices: ["Acute care", "Outpatient", "Diagnostics"],
    typicalProducts: ["Encounters", "Care pathways"],
    typicalCustomers: ["Patients", "Payers"],
    typicalSuppliers: ["Med devices", "Pharma", "Labs"],
    typicalLocations: ["Facilities", "Clinics"],
    defaultGoals: ["Improve throughput", "Lower readmission risk"],
    defaultKpis: ["Throughput", "Readmission risk"],
    painPoints: ["Capacity", "Coordination", "Compliance"],
    reasoningDomains: ["care pathways", "capacity", "compliance", "outcomes"],
  }),
  entry("legal", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Litigation", "Corporate", "Admin"],
    typicalServices: ["Counsel", "Litigation", "Contracts"],
    typicalProducts: ["Matters", "Retainers"],
    typicalCustomers: ["Clients"],
    typicalSuppliers: ["Research", "Court services"],
    typicalLocations: ["Offices"],
    defaultGoals: ["Improve realization", "Meet deadlines"],
    defaultKpis: ["Realization", "Matter aging"],
    painPoints: ["Deadline risk", "Unbilled time"],
    reasoningDomains: ["cases", "clients", "deadlines", "billing"],
  }),
  entry("manufacturing", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Production", "Quality", "Supply Chain", "Maintenance"],
    typicalServices: ["Make-to-order", "Make-to-stock"],
    typicalProducts: ["Finished goods", "Components"],
    typicalCustomers: ["Distributors", "OEMs"],
    typicalSuppliers: ["Raw materials", "Parts"],
    typicalLocations: ["Plants", "Warehouses"],
    defaultGoals: ["Raise yield", "Cut downtime"],
    defaultKpis: ["Yield", "Downtime", "Scrap"],
    painPoints: ["Bottlenecks", "Quality escapes"],
    reasoningDomains: ["production", "quality", "inventory", "maintenance"],
  }),
  entry("retail", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Store Ops", "Merchandising", "Inventory"],
    typicalServices: ["In-store", "Omnichannel"],
    typicalProducts: ["SKU catalog"],
    typicalCustomers: ["Shoppers"],
    typicalSuppliers: ["Brands", "Distributors"],
    typicalLocations: ["Stores", "DC"],
    defaultGoals: ["Improve sell-through", "Grow basket size"],
    defaultKpis: ["Sell-through", "Basket size"],
    painPoints: ["Stockouts", "Markdowns"],
    reasoningDomains: ["inventory", "assortment", "pricing", "customers"],
  }),
  entry("construction", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Field", "Estimating", "Safety", "PM"],
    typicalServices: ["Build", "Renovate", "Maintain"],
    typicalProducts: ["Projects", "Change orders"],
    typicalCustomers: ["Owners", "GCs"],
    typicalSuppliers: ["Materials", "Subs"],
    typicalLocations: ["Jobsites", "Yard"],
    defaultGoals: ["Protect margins", "Hit schedule"],
    defaultKpis: ["Job margin", "Schedule variance"],
    painPoints: ["Weather", "Labor", "Change orders"],
    reasoningDomains: ["jobsites", "crews", "materials", "safety"],
  }),
  entry("consulting", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Delivery", "Sales", "Ops"],
    typicalServices: ["Advisory", "Implementation"],
    typicalProducts: ["Engagements"],
    typicalCustomers: ["Enterprise clients", "SMB"],
    typicalSuppliers: ["Contractors", "Tools"],
    typicalLocations: ["Client sites", "Remote"],
    defaultGoals: ["Raise utilization", "Improve engagement health"],
    defaultKpis: ["Utilization", "Engagement health"],
    painPoints: ["Bench time", "Scope creep"],
    reasoningDomains: ["engagements", "utilization", "deliverables", "accounts"],
  }),
  entry("agency", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Accounts", "Creative", "Strategy", "Media"],
    typicalServices: ["Campaigns", "Retainers", "Content"],
    typicalProducts: ["Creative assets", "Media plans"],
    typicalCustomers: ["Brand clients"],
    typicalSuppliers: ["Freelancers", "Ad platforms"],
    typicalLocations: ["Studio", "Remote"],
    defaultGoals: ["Protect retainers", "Improve campaign ROI"],
    defaultKpis: ["Retainer health", "Campaign ROI"],
    painPoints: ["Capacity", "Revisions", "Attribution"],
    reasoningDomains: ["clients", "campaigns", "retainers", "creative capacity"],
  }),
  entry("real_estate", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Sales", "Marketing", "Transactions"],
    typicalServices: ["Buy", "Sell", "Lease"],
    typicalProducts: ["Listings"],
    typicalCustomers: ["Buyers", "Sellers", "Tenants"],
    typicalSuppliers: ["Photographers", "Inspectors"],
    typicalLocations: ["Market areas"],
    defaultGoals: ["Shorten days on market", "Raise showing conversion"],
    defaultKpis: ["Days on market", "Showing conversion"],
    painPoints: ["Lead quality", "Listing velocity"],
    reasoningDomains: ["listings", "clients", "showings", "pipeline"],
  }),
  entry("education", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Academics", "Admissions", "Student Success"],
    typicalServices: ["Programs", "Tutoring", "Certification"],
    typicalProducts: ["Courses"],
    typicalCustomers: ["Students", "Parents"],
    typicalSuppliers: ["Content", "Facilities"],
    typicalLocations: ["Campus", "Online"],
    defaultGoals: ["Grow enrollment", "Improve completion"],
    defaultKpis: ["Enrollment", "Completion rate"],
    painPoints: ["Retention", "Capacity"],
    reasoningDomains: ["enrollment", "curriculum", "outcomes", "faculty load"],
  }),
  entry("logistics", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Dispatch", "Warehouse", "Fleet"],
    typicalServices: ["Freight", "Last mile", "3PL"],
    typicalProducts: ["Shipments"],
    typicalCustomers: ["Shippers", "Retailers"],
    typicalSuppliers: ["Carriers", "Fuel", "Packaging"],
    typicalLocations: ["Hubs", "Routes"],
    defaultGoals: ["Improve on-time rate", "Lower cost per mile"],
    defaultKpis: ["On-time rate", "Cost per mile"],
    painPoints: ["Empty miles", "Dock congestion"],
    reasoningDomains: ["fleet", "routes", "warehouses", "SLAs"],
  }),
  entry("warehouse", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Inbound", "Outbound", "Inventory"],
    typicalServices: ["Storage", "Fulfillment"],
    typicalProducts: ["Picks", "Packs"],
    typicalCustomers: ["Merchants", "Brands"],
    typicalSuppliers: ["Packaging", "Equipment"],
    typicalLocations: ["Warehouse floors"],
    defaultGoals: ["Raise inventory turns", "Improve pick accuracy"],
    defaultKpis: ["Inventory turns", "Pick accuracy"],
    painPoints: ["Slotting", "Labor peaks"],
    reasoningDomains: ["slotting", "picks", "inventory", "labor"],
  }),
  entry("automotive", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Sales", "Service", "Parts", "F&I"],
    typicalServices: ["Vehicle sales", "Service", "Parts"],
    typicalProducts: ["Vehicles", "RO tickets"],
    typicalCustomers: ["Buyers", "Service guests"],
    typicalSuppliers: ["OEMs", "Parts distributors"],
    typicalLocations: ["Showroom", "Service bays"],
    defaultGoals: ["Improve lot turn", "Raise service absorption"],
    defaultKpis: ["Lot turn", "Service absorption"],
    painPoints: ["Aged inventory", "Technician capacity"],
    reasoningDomains: ["inventory", "service bays", "F&I", "customers"],
  }),
  entry("beauty", {
    defaultSize: "micro",
    defaultCurrency: "USD",
    defaultDepartments: ["Front Desk", "Stylists", "Retail"],
    typicalServices: ["Hair", "Nails", "Skin"],
    typicalProducts: ["Appointments", "Retail SKUs"],
    typicalCustomers: ["Clients"],
    typicalSuppliers: ["Beauty brands"],
    typicalLocations: ["Salon floor"],
    defaultGoals: ["Raise rebooking", "Improve chair utilization"],
    defaultKpis: ["Rebooking rate", "Chair utilization"],
    painPoints: ["No-shows", "Retail attach"],
    reasoningDomains: ["appointments", "stylists", "retail attach", "memberships"],
  }),
  entry("fitness", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Floor", "Training", "Membership"],
    typicalServices: ["Memberships", "Classes", "PT"],
    typicalProducts: ["Memberships", "Sessions"],
    typicalCustomers: ["Members"],
    typicalSuppliers: ["Equipment", "Apparel"],
    typicalLocations: ["Gym floor", "Studios"],
    defaultGoals: ["Improve retention", "Fill classes"],
    defaultKpis: ["Member retention", "Class fill"],
    painPoints: ["Churn", "Peak crowding"],
    reasoningDomains: ["memberships", "classes", "trainers", "retention"],
  }),
  entry("agriculture", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Field", "Operations", "Sales"],
    typicalServices: ["Crop", "Livestock", "Processing"],
    typicalProducts: ["Yield", "Commodities"],
    typicalCustomers: ["Buyers", "Co-ops"],
    typicalSuppliers: ["Seed", "Feed", "Equipment"],
    typicalLocations: ["Fields", "Facilities"],
    defaultGoals: ["Raise yield", "Control input cost"],
    defaultKpis: ["Yield per acre", "Input cost"],
    painPoints: ["Weather", "Input inflation"],
    reasoningDomains: ["yield", "inputs", "equipment", "supply chain"],
  }),
  entry("transport", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Operations", "Fleet", "Customer Service"],
    typicalServices: ["Passenger", "Cargo"],
    typicalProducts: ["Trips", "Contracts"],
    typicalCustomers: ["Passengers", "Shippers"],
    typicalSuppliers: ["Fuel", "Maintenance"],
    typicalLocations: ["Depots", "Routes"],
    defaultGoals: ["Improve OTP", "Raise fleet utilization"],
    defaultKpis: ["OTP", "Fleet utilization"],
    painPoints: ["Delays", "Maintenance"],
    reasoningDomains: ["fleet", "schedules", "maintenance", "safety"],
  }),
  entry("insurance", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Underwriting", "Claims", "Distribution"],
    typicalServices: ["Policies", "Claims"],
    typicalProducts: ["Coverage products"],
    typicalCustomers: ["Policyholders"],
    typicalSuppliers: ["Reinsurers", "Adjusters"],
    typicalLocations: ["Branches", "Digital"],
    defaultGoals: ["Improve retention", "Control loss ratio"],
    defaultKpis: ["Loss ratio", "Policy retention"],
    painPoints: ["Claims cycle", "Fraud"],
    reasoningDomains: ["policies", "claims", "underwriting", "retention"],
  }),
  entry("finance", {
    defaultSize: "large",
    defaultCurrency: "USD",
    defaultDepartments: ["Treasury", "Risk", "Ops"],
    typicalServices: ["Capital", "Lending", "Markets"],
    typicalProducts: ["Financial products"],
    typicalCustomers: ["Institutions", "Clients"],
    typicalSuppliers: ["Data", "Vendors"],
    typicalLocations: ["HQ", "Branches"],
    defaultGoals: ["Grow AUM", "Lower NPL"],
    defaultKpis: ["AUM", "NPL ratio"],
    painPoints: ["Risk", "Regulation"],
    reasoningDomains: ["portfolios", "risk", "liquidity", "compliance"],
  }),
  entry("financial_services", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Advisory", "Ops", "Compliance"],
    typicalServices: ["Planning", "Wealth", "Tax"],
    typicalProducts: ["Plans", "Portfolios"],
    typicalCustomers: ["Households", "Businesses"],
    typicalSuppliers: ["Custodians", "Platforms"],
    typicalLocations: ["Offices", "Virtual"],
    defaultGoals: ["Grow client AUM", "Stay compliant"],
    defaultKpis: ["Client AUM", "Compliance score"],
    painPoints: ["KYC load", "Advice capacity"],
    reasoningDomains: ["clients", "portfolios", "compliance", "planning"],
  }),
  entry("technology", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Engineering", "Product", "GTM", "Support"],
    typicalServices: ["Software", "Platforms", "Support"],
    typicalProducts: ["Products", "APIs"],
    typicalCustomers: ["Users", "Enterprises"],
    typicalSuppliers: ["Cloud", "Tooling"],
    typicalLocations: ["HQ", "Remote"],
    defaultGoals: ["Improve uptime", "Accelerate releases"],
    defaultKpis: ["Uptime", "Release cadence"],
    painPoints: ["Incidents", "Roadmap drag"],
    reasoningDomains: ["product", "reliability", "roadmap", "customers"],
  }),
  entry("saas", {
    defaultSize: "medium",
    defaultCurrency: "USD",
    defaultDepartments: ["Product", "CS", "Sales", "Engineering"],
    typicalServices: ["Subscriptions", "Support", "Onboarding"],
    typicalProducts: ["Plans", "Seats"],
    typicalCustomers: ["Subscribers"],
    typicalSuppliers: ["Cloud", "Billing"],
    typicalLocations: ["Remote", "HQ"],
    defaultGoals: ["Raise NRR", "Lower churn"],
    defaultKpis: ["NRR", "Churn"],
    painPoints: ["Activation", "Expansion"],
    reasoningDomains: ["subscriptions", "usage", "churn", "expansion"],
  }),
  entry("ecommerce", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Merchandising", "Growth", "Fulfillment"],
    typicalServices: ["Online store", "Fulfillment"],
    typicalProducts: ["Catalog SKUs"],
    typicalCustomers: ["Online shoppers"],
    typicalSuppliers: ["Vendors", "3PL"],
    typicalLocations: ["Storefront", "FC"],
    defaultGoals: ["Raise conversion", "Grow LTV"],
    defaultKpis: ["Conversion rate", "LTV"],
    painPoints: ["CAC", "Returns"],
    reasoningDomains: ["catalog", "conversion", "fulfillment", "LTV"],
  }),
  entry("accounting", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Tax", "Bookkeeping", "Advisory"],
    typicalServices: ["Bookkeeping", "Tax", "CFO advisory"],
    typicalProducts: ["Engagements", "Filings"],
    typicalCustomers: ["SMB clients"],
    typicalSuppliers: ["Software", "Specialists"],
    typicalLocations: ["Office", "Remote"],
    defaultGoals: ["Improve realization", "File on time"],
    defaultKpis: ["Realization", "Filing on-time"],
    painPoints: ["Seasonality", "Write-offs"],
    reasoningDomains: ["clients", "filings", "books", "deadlines"],
  }),
  entry("freelancer", {
    defaultSize: "solo",
    defaultCurrency: "USD",
    defaultDepartments: ["Delivery", "Sales"],
    typicalServices: ["Project work", "Retainers"],
    typicalProducts: ["Deliverables"],
    typicalCustomers: ["Clients"],
    typicalSuppliers: ["Tools", "Contractors"],
    typicalLocations: ["Remote"],
    defaultGoals: ["Grow pipeline", "Raise utilization"],
    defaultKpis: ["Pipeline value", "Utilization"],
    painPoints: ["Feast/famine", "Collections"],
    reasoningDomains: ["pipeline", "delivery", "cashflow", "positioning"],
  }),
  entry("government", {
    defaultSize: "enterprise",
    defaultCurrency: "USD",
    defaultDepartments: ["Programs", "Operations", "Citizen Services"],
    typicalServices: ["Public services", "Programs"],
    typicalProducts: ["Service cases"],
    typicalCustomers: ["Constituents"],
    typicalSuppliers: ["Vendors", "Contractors"],
    typicalLocations: ["Agencies", "Field"],
    defaultGoals: ["Hit service levels", "Improve satisfaction"],
    defaultKpis: ["Service level", "Constituent satisfaction"],
    painPoints: ["Bureaucracy", "Capacity"],
    reasoningDomains: ["programs", "service levels", "compliance", "constituents"],
  }),
  entry("nonprofit", {
    defaultSize: "small",
    defaultCurrency: "USD",
    defaultDepartments: ["Programs", "Fundraising", "Ops"],
    typicalServices: ["Programs", "Outreach"],
    typicalProducts: ["Impact initiatives"],
    typicalCustomers: ["Beneficiaries", "Donors"],
    typicalSuppliers: ["Vendors", "Partners"],
    typicalLocations: ["HQ", "Field"],
    defaultGoals: ["Improve donor retention", "Raise program efficiency"],
    defaultKpis: ["Donor retention", "Program efficiency"],
    painPoints: ["Funding cycles", "Reporting load"],
    reasoningDomains: ["donors", "programs", "impact", "fundraising"],
  }),
] as const;

export function getCatalogEntry(type: BusinessType): BusinessCatalogEntry {
  const found = BUSINESS_CATALOG.find((item) => item.type === type);
  if (!found) {
    throw new Error(`No catalog entry for business type: ${type}`);
  }
  return found;
}

export function listCatalog(): readonly BusinessCatalogEntry[] {
  return BUSINESS_CATALOG;
}

/** Ensure every BusinessType has catalog coverage (dev-time guard). */
export function assertCatalogComplete(): void {
  for (const meta of BUSINESS_TYPE_META) {
    getCatalogEntry(meta.type);
  }
}
