/**
 * Remaining automation trigger/action catalog translations.
 */
const LOCALES = ["de","fa","zh-CN","zh-TW","ja","nl","fr","es","it","pt","ru","tr","ar","ko","pl","uk","hi","id","vi"];

function L(rows) {
  const out = {};
  LOCALES.forEach((code, i) => { out[code] = rows[i]; });
  return out;
}

export const ENGINE_TRANSLATIONS = {
  "automation.triggers.customer_created.description": L(["Wird ausgelöst, wenn ein CRM-KundenDatensatz erstellt wird.","وقتی یک رکورد مشتری در CRM ایجاد شود فعال می‌شود.","在创建 CRM 客户记录时触发。","在建立 CRM 客戶記錄時觸發。","CRM の顧客レコードが作成されたときに発火します。","Wordt geactiveerd wanneer een CRM-klantrecord wordt aangemaakt.","Se déclenche lorsqu’un client CRM est créé.","Se dispara cuando se crea un cliente CRM.","Si attiva quando viene creato un cliente CRM.","Dispara quando um cliente CRM é criado.","Срабатывает при создании клиента CRM.","Bir CRM müşteri kaydı oluşturulduğunda tetiklenir.","يُشغَّل عند إنشاء سجل عميل في CRM.","CRM 고객 기록이 생성되면 실행됩니다.","Uruchamia się po utworzeniu klienta CRM.","Спрацьовує, коли створюється клієнт CRM.","CRM ग्राहक रिकॉर्ड बनने पर चलता है.","Dipicu saat catatan pelanggan CRM dibuat.","Kích hoạt khi tạo bản ghi khách hàng CRM."]),
  "automation.triggers.project_created.description": L(["Wird ausgelöst, wenn ein Projekt erstellt wird.","وقتی یک پروژه ایجاد شود فعال می‌شود.","在创建项目时触发。","在建立專案時觸發。","プロジェクトが作成されたときに発火します。","Wordt geactiveerd wanneer een project wordt aangemaakt.","Se déclenche lorsqu’un projet est créé.","Se dispara cuando se crea un proyecto.","Si attiva quando viene creato un progetto.","Dispara quando um projeto é criado.","Срабатывает при создании проекта.","Bir proje oluşturulduğunda tetiklenir.","يُشغَّل عند إنشاء مشروع.","프로젝트가 생성되면 실행됩니다.","Uruchamia się po utworzeniu projektu.","Спрацьовує, коли створюється проєкт.","प्रोजेक्ट बनने पर चलता है.","Dipicu saat proyek dibuat.","Kích hoạt khi tạo dự án."]),
  "automation.triggers.invoice_issued.label": L(["Rechnung ausgestellt","صدور فاکتور","已开具发票","已開立發票","請求書発行","Factuur uitgegeven","Facture émise","Factura emitida","Fattura emessa","Fatura emitida","Счёт выставлен","Fatura kesildi","إصدار فاتورة","송장 발행","Wystawiono fakturę","Рахунок виставлено","चालान जारी","Faktur diterbitkan","Hóa đơn đã phát hành"]),
  "automation.triggers.invoice_issued.description": L(["Wird ausgelöst, wenn eine Rechnung ausgestellt wird.","وقتی فاکتور صادر شود فعال می‌شود.","在开具发票时触发。","在開立發票時觸發。","請求書が発行されたときに発火します。","Wordt geactiveerd wanneer een factuur wordt uitgegeven.","Se déclenche lorsqu’une facture est émise.","Se dispara cuando se emite una factura.","Si attiva quando viene emessa una fattura.","Dispara quando uma fatura é emitida.","Срабатывает при выставлении счёта.","Bir fatura kesildiğinde tetiklenir.","يُشغَّل عند إصدار فاتورة.","송장이 발행되면 실행됩니다.","Uruchamia się po wystawieniu faktury.","Спрацьовує, коли виставляється рахунок.","चालान जारी होने पर चलता है.","Dipicu saat faktur diterbitkan.","Kích hoạt khi phát hành hóa đơn."]),
  "automation.triggers.task_completed.description": L(["Wird ausgelöst, wenn eine Aufgabe als erledigt markiert wird.","وقتی وظیفه‌ای تکمیل شود فعال می‌شود.","在任务标记为完成时触发。","在任務標記為完成時觸發。","タスクが完了したときに発火します。","Wordt geactiveerd wanneer een taak als voltooid wordt gemarkeerd.","Se déclenche lorsqu’une tâche est marquée comme terminée.","Se dispara cuando una tarea se marca como completada.","Si attiva quando un’attività viene contrassegnata come completata.","Dispara quando uma tarefa é marcada como concluída.","Срабатывает, когда задача отмечается выполненной.","Bir görev tamamlandı olarak işaretlendiğinde tetiklenir.","يُشغَّل عند تعليم مهمة كمكتملة.","작업이 완료로 표시되면 실행됩니다.","Uruchamia się po oznaczeniu zadania jako ukończone.","Спрацьовує, коли завдання позначено виконаним.","कार्य पूर्ण चिह्नित होने पर चलता है.","Dipicu saat tugas ditandai selesai.","Kích hoạt khi nhiệm vụ được đánh dấu hoàn tất."]),
  "automation.triggers.document_uploaded.description": L(["Wird ausgelöst, wenn ein Dokument hochgeladen wird.","وقتی سندی بارگذاری شود فعال می‌شود.","在上传文档时触发。","在上傳文件時觸發。","ドキュメントがアップロードされたときに発火します。","Wordt geactiveerd wanneer een document wordt geüpload.","Se déclenche lorsqu’un document est téléversé.","Se dispara cuando se carga un documento.","Si attiva quando viene caricato un documento.","Dispara quando um documento é enviado.","Срабатывает при загрузке документа.","Bir belge yüklendiğinde tetiklenir.","يُشغَّل عند رفع مستند.","문서가 업로드되면 실행됩니다.","Uruchamia się po przesłaniu dokumentu.","Спрацьовує, коли документ завантажено.","दस्तावेज़ अपलोड होने पर चलता है.","Dipicu saat dokumen diunggah.","Kích hoạt khi tài liệu được tải lên."]),
  "automation.triggers.user_invited.label": L(["Benutzer eingeladen","دعوت کاربر","已邀请用户","已邀請使用者","ユーザー招待","Gebruiker uitgenodigd","Utilisateur invité","Usuario invitado","Utente invitato","Utilizador convidado","Пользователь приглашён","Kullanıcı davet edildi","تمت دعوة مستخدم","사용자 초대됨","Zaproszono użytkownika","Користувача запрошено","उपयोगकर्ता आमंत्रित","Pengguna diundang","Đã mời người dùng"]),
  "automation.triggers.user_invited.description": L(["Wird ausgelöst, wenn ein Teammitglied eingeladen wird.","وقتی عضوی به تیم دعوت شود فعال می‌شود.","在邀请团队成员时触发。","在邀請團隊成員時觸發。","チームメンバーが招待されたときに発火します。","Wordt geactiveerd wanneer een teammid wordt uitgenodigd.","Se déclenche lorsqu’un membre d’équipe est invité.","Se dispara cuando se invita a un miembro del equipo.","Si attiva quando un membro del team viene invitato.","Dispara quando um membro da equipa é convidado.","Срабатывает при приглашении участника команды.","Bir ekip üyesi davet edildiğinde tetiklenir.","يُشغَّل عند دعوة عضو في الفريق.","팀 멤버가 초대되면 실행됩니다.","Uruchamia się po zaproszeniu członka zespołu.","Спрацьовує, коли запрошують учасника команди.","टीम सदस्य आमंत्रित होने पर चलता है.","Dipicu saat anggota tim diundang.","Kích hoạt khi một thành viên nhóm được mời."]),
  "automation.triggers.schedule.description": L(["Cron- / Intervall-Zeitplan.","محرک زمان‌بندی کرون / بازه‌ای.","Cron / 间隔计划触发器。","Cron／間隔排程觸發。","Cron / 間隔スケジュールのトリガー。","Cron-/intervalschema.","Déclencheur de planification cron / intervalle.","Disparador de programación cron / intervalo.","Trigger di pianificazione cron / intervallo.","Acionador de agendamento cron / intervalo.","Триггер расписания cron / интервала.","Cron / aralık zamanlama tetikleyicisi.","مشغّل جدولة cron / فاصل زمني.","Cron / 간격 일정 트리거.","Wyzwalacz harmonogramu cron / interwału.","Тригер розкладу cron / інтервалу.","क्रॉन / अंतराल शेड्यूल ट्रिगर.","Pemicu jadwal cron / interval.","Trình kích hoạt lịch cron / khoảng thời gian."]),
  "automation.triggers.webhook.label": L(["Webhook","وب‌هوک","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook","Webhook"]),
  "automation.triggers.webhook.description": L(["Eingehender HTTP-Webhook.","وب‌هوک ورودی HTTP.","入站 HTTP Webhook。","傳入 HTTP Webhook。","受信 HTTP Webhook。","Inkomende HTTP-webhook.","Webhook HTTP entrant.","Webhook HTTP entrante.","Webhook HTTP in ingresso.","Webhook HTTP de entrada.","Входящий HTTP-webhook.","Gelen HTTP webhook.","Webhook HTTP وارد.","수신 HTTP 웹훅.","Przychodzący webhook HTTP.","Вхідний HTTP-webhook.","इनबाउंड HTTP वेबहुक.","Webhook HTTP masuk.","Webhook HTTP đến."]),
  "automation.triggers.api_event.label": L(["API-Ereignis","رویداد API","API 事件","API 事件","API イベント","API-gebeurtenis","Événement API","Evento API","Evento API","Evento de API","Событие API","API olayı","حدث API","API 이벤트","Zdarzenie API","Подія API","API इवेंट","Peristiwa API","Sự kiện API"]),
  "automation.triggers.api_event.description": L(["Allgemeines API-Domänenereignis.","رویداد دامنه‌ای عمومی API.","通用 API 域事件。","一般 API 網域事件。","汎用 API ドメインイベント。","Algemeen API-domeinevent.","Événement de domaine API générique.","Evento de dominio API genérico.","Evento di dominio API generico.","Evento de domínio API genérico.","Общее доменное событие API.","Genel API etki alanı olayı.","حدث نطاق API عام.","일반 API 도메인 이벤트.","Ogólne zdarzenie domeny API.","Загальна доменна подія API.","सामान्य API डोमेन इवेंट.","Peristiwa domain API umum.","Sự kiện miền API chung."]),
  "automation.triggers.ai_event.label": L(["KI-Ereignis","رویداد هوش مصنوعی","AI 事件","AI 事件","AI イベント","AI-gebeurtenis","Événement IA","Evento de IA","Evento IA","Evento de IA","Событие ИИ","AI olayı","حدث الذكاء الاصطناعي","AI 이벤트","Zdarzenie AI","Подія ШІ","AI इवेंट","Peristiwa AI","Sự kiện AI"]),
  "automation.triggers.ai_event.description": L(["KI-Signal (Abschluss, Erkenntnis, Agentenschritt).","سیگنال هوش مصنوعی (تکمیل، بینش، گام عامل).","AI 信号（完成、洞察、代理步骤）。","AI 訊號（完成、洞察、代理步驟）。","AI シグナル（完了、洞察、エージェント手順）。","AI-signaal (voltooiing, inzicht, agentstap).","Signal IA (achèvement, insight, étape d’agent).","Señal de IA (finalización, insight, paso de agente).","Segnale IA (completamento, insight, passo agente).","Sinal de IA (conclusão, insight, passo de agente).","Сигнал ИИ (завершение, инсайт, шаг агента).","AI sinyali (tamamlanma, içgörü, aracı adımı).","إشارة ذكاء اصطناعي (اكتمال، رؤية، خطوة وكيل).","AI 신호(완료, 인사이트, 에이전트 단계).","Sygnał AI (ukończenie, wgląd, krok agenta).","Сигнал ШІ (завершення, інсайт, крок агента).","AI संकेत (पूर्णता, इनसाइट, एजेंट चरण).","Sinyal AI (selesai, wawasan, langkah agen).","Tín hiệu AI (hoàn tất, insight, bước tác nhân)."]),
  "automation.triggers.manual.label": L(["Manueller Auslöser","محرک دستی","手动触发","手動觸發","手動トリガー","Handmatige trigger","Déclencheur manuel","Disparador manual","Trigger manuale","Acionador manual","Ручной триггер","Manuel tetikleyici","مشغّل يدوي","수동 트리거","Wyzwalacz ręczny","Ручний тригер","मैनुअल ट्रिगर","Pemicu manual","Kích hoạt thủ công"]),
  "automation.triggers.manual.description": L(["Bei Bedarf aus der Automatisierungs-UI oder API.","اجرا به‌صورت دستی از رابط یا API.","按需从自动化界面或 API 运行。","依需求從自動化介面或 API 執行。","自動化 UI または API からオンデマンド実行。","On-demand vanuit de automatiserings-UI of API.","Exécution à la demande depuis l’UI ou l’API.","Ejecutar bajo demanda desde la UI o la API.","Esecuzione on demand da UI o API.","Executar on-demand na UI ou API.","Запуск по требованию из UI или API.","UI veya API’den isteğe bağlı çalıştırma.","تشغيل عند الطلب من الواجهة أو API.","자동화 UI 또는 API에서 필요할 때 실행.","Uruchomienie na żądanie z UI lub API.","Запуск на вимогу з UI або API.","UI या API से ऑन-डिमांड चलाएँ.","Jalankan on-demand dari UI atau API.","Chạy theo yêu cầu từ giao diện hoặc API."]),
  "automation.actions.customer_create.description": L(["CRM-Kundendatensatz erstellen.","ایجاد رکورد مشتری در CRM.","创建 CRM 客户记录。","建立 CRM 客戶記錄。","CRM の顧客レコードを作成します。","Een CRM-klantrecord aanmaken.","Créer une fiche client CRM.","Crear un registro de cliente CRM.","Crea un record cliente CRM.","Criar um registo de cliente CRM.","Создать запись клиента CRM.","CRM müşteri kaydı oluştur.","إنشاء سجل عميل في CRM.","CRM 고객 기록을 만듭니다.","Utwórz rekord klienta CRM.","Створити запис клієнта CRM.","CRM ग्राहक रिकॉर्ड बनाएँ.","Buat catatan pelanggan CRM.","Tạo bản ghi khách hàng CRM."]),
  "automation.actions.customer_update.description": L(["Felder eines Kunden aktualisieren.","به‌روزرسانی فیلدهای مشتری.","更新客户字段。","更新客戶欄位。","顧客のフィールドを更新します。","Velden van een klant bijwerken.","Mettre à jour les champs d’un client.","Actualizar campos de un cliente.","Aggiorna i campi di un cliente.","Atualizar campos de um cliente.","Обновить поля клиента.","Müşteri alanlarını güncelle.","تحديث حقول العميل.","고객 필드를 업데이트합니다.","Zaktualizuj pola klienta.","Оновити поля клієнта.","ग्राहक फ़ील्ड अपडेट करें.","Perbarui kolom pelanggan.","Cập nhật trường khách hàng."]),
  "automation.actions.project_create.description": L(["Projekt aus dem Workflow-Kontext erstellen.","ایجاد پروژه از بافت گردش‌کار.","从工作流上下文创建项目。","從工作流程內容建立專案。","ワークフローコンテキストからプロジェクトを作成します。","Een project vanuit de workflowcontext aanmaken.","Créer un projet à partir du contexte du workflow.","Crear un proyecto desde el contexto del flujo.","Crea un progetto dal contesto del workflow.","Criar um projeto a partir do contexto do fluxo.","Создать проект из контекста сценария.","İş akışı bağlamından proje oluştur.","إنشاء مشروع من سياق سير العمل.","워크플로 컨텍스트에서 프로젝트를 만듭니다.","Utwórz projekt z kontekstu przepływu.","Створити проєкт із контексту процесу.","वर्कफ़्लो संदर्भ से प्रोजेक्ट बनाएँ.","Buat proyek dari konteks alur kerja.","Tạo dự án từ ngữ cảnh quy trình."]),
  "automation.actions.document_generate.label": L(["Dokument erzeugen","تولید سند","生成文档","產生文件","ドキュメント生成","Document genereren","Générer un document","Generar documento","Genera documento","Gerar documento","Создать документ","Belge oluştur","إنشاء مستند","문서 생성","Wygeneruj dokument","Згенерувати документ","दस्तावेज़ बनाएँ","Buat dokumen","Tạo tài liệu"]),
  "automation.actions.document_generate.description": L(["Dokument aus einer Vorlage erzeugen.","تولید سند از روی قالب.","从模板生成文档。","從範本產生文件。","テンプレートからドキュメントを生成します。","Een document uit een sjabloon genereren.","Générer un document à partir d’un modèle.","Generar un documento desde una plantilla.","Genera un documento da un modello.","Gerar um documento a partir de um modelo.","Создать документ из шаблона.","Şablondan belge oluştur.","إنشاء مستند من قالب.","템플릿에서 문서를 생성합니다.","Wygeneruj dokument z szablonu.","Згенерувати документ із шаблону.","टेम्पलेट से दस्तावेज़ बनाएँ.","Buat dokumen dari templat.","Tạo tài liệu từ mẫu."]),
  "automation.actions.notification_send.description": L(["In-App-Benachrichtigung senden.","ارسال اعلان درون‌برنامه.","发送应用内通知。","傳送應用程式內通知。","アプリ内通知を送信します。","Een in-app-melding sturen.","Envoyer une notification in-app.","Enviar una notificación in-app.","Invia una notifica in-app.","Enviar uma notificação in-app.","Отправить уведомление в приложении.","Uygulama içi bildirim gönder.","إرسال إشعار داخل التطبيق.","인앱 알림을 보냅니다.","Wyślij powiadomienie w aplikacji.","Надіслати сповіщення в застосунку.","इन-ऐप सूचना भेजें.","Kirim notifikasi dalam aplikasi.","Gửi thông báo trong ứng dụng."]),
  "automation.actions.email_send.description": L(["E-Mail über den Mail-Provider einreihen.","صف‌کردن ایمیل از طریق ارائه‌دهنده.","通过邮件服务排队发送电子邮件。","透過郵件服務將電子郵件加入佇列。","メールプロバイダー経由でメールをキューします。","Een e-mail via de mailprovider in de wachtrij zetten.","Mettre un e-mail en file d’attente via le fournisseur.","Poner un correo en cola a través del proveedor.","Accoda un’e-mail tramite il provider.","Colocar um e-mail na fila via fornecedor.","Поставить письмо в очередь через провайдера.","Posta sağlayıcısı üzerinden e-posta kuyruğa al.","وضع بريد في قائمة الانتظار عبر الموفر.","메일 제공자를 통해 이메일을 대기열에 넣습니다.","Dodaj e-mail do kolejki przez dostawcę.","Поставити лист у чергу через провайдера.","मेल प्रदाता के माध्यम से ईमेल कतार में डालें.","Antre email melalui penyedia mail.","Xếp hàng email qua nhà cung cấp thư."]),
  "automation.actions.api_call.label": L(["API aufrufen","فراخوانی API","调用 API","呼叫 API","API 呼び出し","API aanroepen","Appeler l’API","Llamar a la API","Chiama API","Chamar API","Вызов API","API çağır","استدعاء API","API 호출","Wywołaj API","Виклик API","API कॉल","Panggil API","Gọi API"]),
  "automation.actions.api_call.description": L(["HTTP-Aufruf an eine externe oder interne API.","فراخوان HTTP به API داخلی یا خارجی.","对内部或外部 API 发起 HTTP 调用。","對內部或外部 API 發出 HTTP 呼叫。","内部または外部 API への HTTP 呼び出し。","HTTP-aanroep naar een interne of externe API.","Appel HTTP vers une API interne ou externe.","Llamada HTTP a una API interna o externa.","Chiamata HTTP a un’API interna o esterna.","Chamada HTTP a uma API interna ou externa.","HTTP-вызов внутреннего или внешнего API.","Dahili veya harici API’ye HTTP çağrısı.","استدعاء HTTP لواجهة API داخلية أو خارجية.","내부 또는 외부 API에 대한 HTTP 호출.","Wywołanie HTTP do wewnętrznego lub zewnętrznego API.","HTTP-виклик внутрішнього або зовнішнього API.","आंतरिक या बाहरी API पर HTTP कॉल.","Panggilan HTTP ke API internal atau eksternal.","Gọi HTTP tới API nội bộ hoặc bên ngoài."]),
  "automation.actions.ai_run.label": L(["KI ausführen","اجرای هوش مصنوعی","运行 AI","執行 AI","AI を実行","AI uitvoeren","Exécuter l’IA","Ejecutar IA","Esegui IA","Executar IA","Запустить ИИ","AI çalıştır","تشغيل الذكاء الاصطناعي","AI 실행","Uruchom AI","Запустити ШІ","AI चलाएँ","Jalankan AI","Chạy AI"]),
  "automation.actions.ai_run.description": L(["KI-Prompt / Agentenschritt mit Kontext ausführen.","اجرای پرامپت / گام عامل با بافت.","使用上下文执行 AI 提示 / 代理步骤。","使用內容執行 AI 提示／代理步驟。","コンテキスト付きで AI プロンプト / エージェント手順を実行します。","Een AI-prompt / agentstap met context uitvoeren.","Exécuter une invite IA / étape d’agent avec contexte.","Ejecutar un prompt de IA / paso de agente con contexto.","Esegui un prompt IA / passo agente con contesto.","Executar um prompt de IA / passo de agente com contexto.","Выполнить промпт ИИ / шаг агента с контекстом.","Bağlamla AI istemi / aracı adımı çalıştır.","تنفيذ موجّه ذكاء اصطناعي / خطوة وكيل مع السياق.","컨텍스트와 함께 AI 프롬프트 / 에이전트 단계를 실행합니다.","Uruchom prompt AI / krok agenta z kontekstem.","Виконати промпт ШІ / крок агента з контекстом.","संदर्भ के साथ AI प्रॉम्प्ट / एजेंट चरण चलाएँ.","Jalankan prompt AI / langkah agen dengan konteks.","Chạy prompt AI / bước tác nhân kèm ngữ cảnh."]),
  "automation.actions.task_assign.label": L(["Aufgabe zuweisen","واگذاری وظیفه","分配任务","指派任務","タスクを割り当て","Taak toewijzen","Assigner une tâche","Asignar tarea","Assegna attività","Atribuir tarefa","Назначить задачу","Görev ata","تعيين مهمة","작업 할당","Przypisz zadanie","Призначити завдання","कार्य असाइन करें","Tetapkan tugas","Gán nhiệm vụ"]),
  "automation.actions.task_assign.description": L(["Eine Aufgabe einem Benutzer zuweisen.","واگذاری وظیفه به کاربر.","将任务分配给用户。","將任務指派給使用者。","タスクをユーザーに割り当てます。","Een taak aan een gebruiker toewijzen.","Assigner une tâche à un utilisateur.","Asignar una tarea a un usuario.","Assegna un’attività a un utente.","Atribuir uma tarefa a um utilizador.","Назначить задачу пользователю.","Bir kullanıcıya görev ata.","تعيين مهمة لمستخدم.","작업을 사용자에게 할당합니다.","Przypisz zadanie użytkownikowi.","Призначити завдання користувачу.","उपयोगकर्ता को कार्य असाइन करें.","Tetapkan tugas ke pengguna.","Gán nhiệm vụ cho người dùng."]),
  "automation.actions.invoice_create.description": L(["Eine Finanzrechnung erstellen.","ایجاد فاکتور مالی.","创建财务发票。","建立財務發票。","財務の請求書を作成します。","Een financiële factuur aanmaken.","Créer une facture financière.","Crear una factura financiera.","Crea una fattura finanziaria.","Criar uma fatura financeira.","Создать финансовый счёт.","Finans faturası oluştur.","إنشاء فاتورة مالية.","재무 송장을 만듭니다.","Utwórz fakturę finansową.","Створити фінансовий рахунок.","वित्त चालान बनाएँ.","Buat faktur keuangan.","Tạo hóa đơn tài chính."]),
  "automation.actions.status_update.description": L(["Status einer Entität in einem Modul aktualisieren.","به‌روزرسانی وضعیت موجودیت در یک ماژول.","更新模块中实体的状态。","更新模組中實體的狀態。","モジュール内エンティティのステータスを更新します。","De status van een entiteit in een module bijwerken.","Mettre à jour le statut d’une entité dans un module.","Actualizar el estado de una entidad en un módulo.","Aggiorna lo stato di un’entità in un modulo.","Atualizar o estado de uma entidade num módulo.","Обновить статус сущности в модуле.","Bir modüldeki varlığın durumunu güncelle.","تحديث حالة كيان في وحدة.","모듈 내 엔터티 상태를 업데이트합니다.","Zaktualizuj status encji w module.","Оновити статус сутності в модулі.","मॉड्यूल में एंटिटी की स्थिति अपडेट करें.","Perbarui status entitas di modul.","Cập nhật trạng thái thực thể trong mô-đun."]),
};
