/**
 * Message catalog loader — AUTO-GENERATED by scripts/i18n/build-bundles.mjs
 * Do not edit manually. Run: node scripts/i18n/build-bundles.mjs
 */

import type { AppLocale } from "./locale";
import { DEFAULT_LOCALE } from "./locale";

import bundle_en from "./bundles/en.json";
import bundle_de from "./bundles/de.json";
import bundle_fa from "./bundles/fa.json";
import bundle_zh_CN from "./bundles/zh-CN.json";
import bundle_zh_TW from "./bundles/zh-TW.json";
import bundle_ja from "./bundles/ja.json";
import bundle_nl from "./bundles/nl.json";
import bundle_nl_BE from "./bundles/nl-BE.json";
import bundle_fr from "./bundles/fr.json";
import bundle_fr_BE from "./bundles/fr-BE.json";
import bundle_de_BE from "./bundles/de-BE.json";
import bundle_es from "./bundles/es.json";
import bundle_it from "./bundles/it.json";
import bundle_pt from "./bundles/pt.json";
import bundle_pt_BR from "./bundles/pt-BR.json";
import bundle_ru from "./bundles/ru.json";
import bundle_tr from "./bundles/tr.json";
import bundle_ar from "./bundles/ar.json";
import bundle_ko from "./bundles/ko.json";
import bundle_pl from "./bundles/pl.json";
import bundle_uk from "./bundles/uk.json";
import bundle_hi from "./bundles/hi.json";
import bundle_id from "./bundles/id.json";
import bundle_vi from "./bundles/vi.json";

export type MessageTree = {
  readonly common: Record<string, unknown>;
  readonly navigation: Record<string, unknown>;
  readonly pricing: Record<string, unknown>;
  readonly billing: Record<string, unknown>;
  readonly settings: Record<string, unknown>;
  readonly errors: Record<string, unknown>;
  readonly dashboard: Record<string, unknown>;
  readonly auth: Record<string, unknown>;
  readonly crm: Record<string, unknown>;
  readonly finance: Record<string, unknown>;
  readonly documents: Record<string, unknown>;
  readonly landing: Record<string, unknown>;
  readonly ui: Record<string, unknown>;
  readonly projects: Record<string, unknown>;
  readonly automation: Record<string, unknown>;
  readonly team: Record<string, unknown>;
  readonly customers: Record<string, unknown>;
  readonly ai: Record<string, unknown>;
  readonly agents: Record<string, unknown>;
  readonly integrations: Record<string, unknown>;
  readonly intelligence: Record<string, unknown>;
  readonly legal: Record<string, unknown>;
  readonly onboarding: Record<string, unknown>;
  readonly creator: Record<string, unknown>;
  readonly backend: Record<string, unknown>;
  readonly workspace: Record<string, unknown>;
  readonly iam: Record<string, unknown>;
};

const CATALOGS: Readonly<Record<AppLocale, MessageTree>> = {
  "en": bundle_en as MessageTree,
  "de": bundle_de as MessageTree,
  "fa": bundle_fa as MessageTree,
  "zh-CN": bundle_zh_CN as MessageTree,
  "zh-TW": bundle_zh_TW as MessageTree,
  "ja": bundle_ja as MessageTree,
  "nl": bundle_nl as MessageTree,
  "nl-BE": bundle_nl_BE as MessageTree,
  "fr": bundle_fr as MessageTree,
  "fr-BE": bundle_fr_BE as MessageTree,
  "de-BE": bundle_de_BE as MessageTree,
  "es": bundle_es as MessageTree,
  "it": bundle_it as MessageTree,
  "pt": bundle_pt as MessageTree,
  "pt-BR": bundle_pt_BR as MessageTree,
  "ru": bundle_ru as MessageTree,
  "tr": bundle_tr as MessageTree,
  "ar": bundle_ar as MessageTree,
  "ko": bundle_ko as MessageTree,
  "pl": bundle_pl as MessageTree,
  "uk": bundle_uk as MessageTree,
  "hi": bundle_hi as MessageTree,
  "id": bundle_id as MessageTree,
  "vi": bundle_vi as MessageTree,
};

export function getCatalog(locale: AppLocale): MessageTree {
  return CATALOGS[locale] ?? CATALOGS[DEFAULT_LOCALE];
}

export function getFallbackCatalog(): MessageTree {
  return CATALOGS[DEFAULT_LOCALE];
}
