import type {
  AutomationKpi,
  WorkflowDefinition,
  WorkflowRun,
  WorkflowTemplate,
} from "./types";

export const AUTOMATION_KPIS: readonly AutomationKpi[] = [
  {
    id: "active",
    label: "Active Workflows",
    value: "24",
    caption: "Enabled in workspace",
    delta: { value: "+3", positive: true },
  },
  {
    id: "runs-today",
    label: "Workflow Runs Today",
    value: "186",
    caption: "Across all triggers",
    delta: { value: "+22", positive: true },
  },
  {
    id: "success",
    label: "Successful Automations",
    value: "172",
    caption: "Today",
    delta: { value: "92.5%", positive: true },
  },
  {
    id: "failed",
    label: "Failed Runs",
    value: "7",
    caption: "Needs attention",
    delta: { value: "-2", positive: true },
  },
  {
    id: "pending",
    label: "Pending Tasks",
    value: "14",
    caption: "Approvals + retries",
    delta: { value: "+1", positive: false },
  },
  {
    id: "avg-time",
    label: "Average Execution Time",
    value: "1.8s",
    caption: "Median 1.2s",
    delta: { value: "-120ms", positive: true },
  },
  {
    id: "ai-suggestions",
    label: "AI Suggestions",
    value: "11",
    caption: "Automation opportunities",
    delta: { value: "+4", positive: true },
  },
];

export const DEFAULT_WORKFLOW: WorkflowDefinition = {
  id: "wf-onboarding",
  name: "Customer Onboarding",
  description: "Welcome sequence when a customer is created.",
  active: true,
  updatedAt: "2026-07-30T12:00:00Z",
  nodes: [
    { id: "n1", type: "trigger", catalogId: "tr-customer", label: "Customer Created", x: 72, y: 168 },
    { id: "n2", type: "action", catalogId: "ac-email", label: "Send Email", x: 312, y: 168 },
    { id: "n3", type: "ai_action", catalogId: "ai-sum", label: "AI Summarization", x: 552, y: 168 },
    { id: "n4", type: "action", catalogId: "ac-task", label: "Create Task", x: 792, y: 168 },
    { id: "n5", type: "condition", catalogId: "el-condition", label: "Condition", x: 552, y: 336 },
    { id: "n6", type: "notification", catalogId: "el-notification", label: "Notification", x: 792, y: 336 },
  ],
  edges: [
    { id: "e1", from: "n1", to: "n2" },
    { id: "e2", from: "n2", to: "n3" },
    { id: "e3", from: "n3", to: "n4" },
    { id: "e4", from: "n3", to: "n5" },
    { id: "e5", from: "n5", to: "n6" },
  ],
};

function previewGraph(
  id: string,
  name: string,
  nodes: WorkflowDefinition["nodes"],
  edges: WorkflowDefinition["edges"],
): WorkflowDefinition {
  return {
    id,
    name,
    description: name,
    active: false,
    updatedAt: "2026-07-30T12:00:00Z",
    nodes,
    edges,
  };
}

export const WORKFLOW_RUNS: readonly WorkflowRun[] = [
  {
    id: "run-1",
    workflowId: "wf-onboarding",
    workflowName: "Customer Onboarding",
    status: "success",
    startedAt: "2026-07-30T15:12:00Z",
    finishedAt: "2026-07-30T15:12:01Z",
    durationMs: 1420,
    trigger: "Customer Created",
    detail: "Welcome email sent · task assigned to Sara M.",
    executedBy: "System · Automation Engine",
    retryAvailable: false,
    input: '{ "customerId": "cust-nordlicht", "source": "crm" }',
    output: '{ "emailId": "msg-441", "taskId": "task-882" }',
    aiSummary: "Onboarding completed cleanly. Customer welcomed and owner task created.",
  },
  {
    id: "run-2",
    workflowId: "wf-invoice-reminder",
    workflowName: "Invoice Reminder",
    status: "success",
    startedAt: "2026-07-30T14:40:00Z",
    finishedAt: "2026-07-30T14:40:01Z",
    durationMs: 980,
    trigger: "Schedule Trigger",
    detail: "Reminder email dispatched for INV-2026-1004.",
    executedBy: "Scheduler",
    retryAvailable: false,
    input: '{ "invoiceId": "INV-2026-1004" }',
    output: '{ "emailId": "msg-512" }',
    aiSummary: "Reminder sent within SLA. No escalation required.",
  },
  {
    id: "run-3",
    workflowId: "wf-lead-followup",
    workflowName: "Lead Follow-up",
    status: "failed",
    startedAt: "2026-07-30T13:05:00Z",
    finishedAt: "2026-07-30T13:05:02Z",
    durationMs: 2100,
    trigger: "Lead Created",
    detail: "Email adapter timeout — retry available.",
    executedBy: "System · Automation Engine",
    retryAvailable: true,
    input: '{ "leadId": "lead-991", "owner": "Tom K." }',
    output: "{}",
    aiSummary: "Follow-up stopped at Send Email. Retry when adapter health recovers.",
    errorMessage: "EmailAdapterTimeout: upstream provider did not respond within 2000ms.",
  },
  {
    id: "run-4",
    workflowId: "wf-content-publish",
    workflowName: "Content Publishing",
    status: "success",
    startedAt: "2026-07-30T11:22:00Z",
    finishedAt: "2026-07-30T11:22:03Z",
    durationMs: 3100,
    trigger: "Campaign Published",
    detail: "Analytics snapshot + notify queued.",
    executedBy: "Creator Studio bridge",
    retryAvailable: false,
    input: '{ "campaignId": "camp-1" }',
    output: '{ "notifyQueued": true }',
    aiSummary: "Publish pipeline completed. Downstream analytics job queued.",
  },
  {
    id: "run-5",
    workflowId: "wf-approval",
    workflowName: "Approval Process",
    status: "pending",
    startedAt: "2026-07-30T10:50:00Z",
    durationMs: 0,
    trigger: "Manual Trigger",
    detail: "Waiting on approval from Tom K.",
    executedBy: "Sara M.",
    retryAvailable: false,
    input: '{ "requestId": "apr-77" }',
    output: '{ "status": "awaiting_approval" }',
    aiSummary: "Human approval gate active. No AI actions pending.",
  },
  {
    id: "run-6",
    workflowId: "wf-lead-followup",
    workflowName: "Lead Follow-up",
    status: "retried",
    startedAt: "2026-07-30T09:18:00Z",
    finishedAt: "2026-07-30T09:18:02Z",
    durationMs: 1650,
    trigger: "Lead Created",
    detail: "Succeeded on second attempt.",
    executedBy: "Retry Queue",
    retryAvailable: false,
    input: '{ "leadId": "lead-880" }',
    output: '{ "emailId": "msg-603" }',
    aiSummary: "Retry recovered a transient adapter failure.",
  },
];

export const WORKFLOW_TEMPLATES: readonly WorkflowTemplate[] = [
  {
    id: "tpl-onboarding",
    name: "Customer Onboarding",
    description: "Welcome email, AI summary, and owner task after customer creation.",
    category: "CRM",
    nodeCount: 6,
    estimatedRuntime: "~2s",
    difficulty: "starter",
    recommendedFor: "Teams onboarding new B2B customers",
    requiredModules: ["AI CRM", "Automation"],
    aiFeatures: ["AI Summarization"],
    preview: DEFAULT_WORKFLOW,
  },
  {
    id: "tpl-invoice",
    name: "Invoice Reminder",
    description: "Scheduled reminders for open invoices with escalation path.",
    category: "Finance",
    nodeCount: 5,
    estimatedRuntime: "~1.2s",
    difficulty: "starter",
    recommendedFor: "Finance ops reducing overdue receivables",
    requiredModules: ["Finance & Tax", "Automation"],
    aiFeatures: [],
    preview: previewGraph(
      "wf-invoice-preview",
      "Invoice Reminder",
      [
        { id: "a1", type: "trigger", catalogId: "tr-schedule", label: "Schedule Trigger", x: 72, y: 168 },
        { id: "a2", type: "condition", catalogId: "el-condition", label: "Condition", x: 312, y: 168 },
        { id: "a3", type: "action", catalogId: "ac-email", label: "Send Email", x: 552, y: 168 },
        { id: "a4", type: "delay", catalogId: "el-delay", label: "Delay", x: 552, y: 336 },
        { id: "a5", type: "notification", catalogId: "el-notification", label: "Notification", x: 792, y: 336 },
      ],
      [
        { id: "x1", from: "a1", to: "a2" },
        { id: "x2", from: "a2", to: "a3" },
        { id: "x3", from: "a3", to: "a4" },
        { id: "x4", from: "a4", to: "a5" },
      ],
    ),
  },
  {
    id: "tpl-lead",
    name: "Lead Follow-up",
    description: "AI email reply plus pipeline status update for new leads.",
    category: "Sales",
    nodeCount: 7,
    estimatedRuntime: "~2.4s",
    difficulty: "intermediate",
    recommendedFor: "Sales teams with high inbound lead volume",
    requiredModules: ["AI CRM", "Automation"],
    aiFeatures: ["AI Email Reply", "AI Routing"],
    preview: previewGraph(
      "wf-lead-preview",
      "Lead Follow-up",
      [
        { id: "b1", type: "trigger", catalogId: "tr-lead", label: "Lead Created", x: 72, y: 168 },
        { id: "b2", type: "ai_action", catalogId: "ai-email", label: "AI Email Reply", x: 312, y: 168 },
        { id: "b3", type: "action", catalogId: "ac-email", label: "Send Email", x: 552, y: 168 },
        { id: "b4", type: "ai_action", catalogId: "ai-route", label: "AI Routing", x: 792, y: 168 },
        { id: "b5", type: "action", catalogId: "ac-update-status", label: "Update Status", x: 552, y: 336 },
      ],
      [
        { id: "y1", from: "b1", to: "b2" },
        { id: "y2", from: "b2", to: "b3" },
        { id: "y3", from: "b3", to: "b4" },
        { id: "y4", from: "b4", to: "b5" },
      ],
    ),
  },
  {
    id: "tpl-welcome",
    name: "Welcome Email",
    description: "Simple welcome sequence on signup.",
    category: "Marketing",
    nodeCount: 3,
    estimatedRuntime: "~0.8s",
    difficulty: "starter",
    recommendedFor: "Any workspace starting with email automation",
    requiredModules: ["Automation"],
    aiFeatures: [],
    preview: previewGraph(
      "wf-welcome-preview",
      "Welcome Email",
      [
        { id: "c1", type: "trigger", catalogId: "tr-customer", label: "Customer Created", x: 96, y: 180 },
        { id: "c2", type: "action", catalogId: "ac-email", label: "Send Email", x: 360, y: 180 },
        { id: "c3", type: "notification", catalogId: "el-notification", label: "Notification", x: 624, y: 180 },
      ],
      [
        { id: "z1", from: "c1", to: "c2" },
        { id: "z2", from: "c2", to: "c3" },
      ],
    ),
  },
  {
    id: "tpl-pipeline",
    name: "Sales Pipeline",
    description: "Stage changes with notifications and tasks.",
    category: "Sales",
    nodeCount: 8,
    estimatedRuntime: "~2.8s",
    difficulty: "advanced",
    recommendedFor: "Teams managing multi-stage deal progression",
    requiredModules: ["AI CRM", "Automation"],
    aiFeatures: ["AI Decision", "AI Recommendations"],
    preview: DEFAULT_WORKFLOW,
  },
  {
    id: "tpl-recruit",
    name: "Recruitment",
    description: "Candidate routing and interview tasks.",
    category: "HR",
    nodeCount: 6,
    estimatedRuntime: "~2.1s",
    difficulty: "intermediate",
    recommendedFor: "Hiring managers and people ops",
    requiredModules: ["Team", "Automation"],
    aiFeatures: ["AI Classification"],
    preview: DEFAULT_WORKFLOW,
  },
  {
    id: "tpl-content",
    name: "Content Publishing",
    description: "Creator Studio publish → notify → analytics.",
    category: "Creator",
    nodeCount: 5,
    estimatedRuntime: "~3.1s",
    difficulty: "intermediate",
    recommendedFor: "Marketing and creator teams",
    requiredModules: ["AI Creator Studio", "Automation"],
    aiFeatures: ["Generate AI Content"],
    preview: DEFAULT_WORKFLOW,
  },
  {
    id: "tpl-approval",
    name: "Approval Process",
    description: "Multi-step approval with AI recommendations.",
    category: "Ops",
    nodeCount: 7,
    estimatedRuntime: "~human gate",
    difficulty: "advanced",
    recommendedFor: "Finance/ops approvals before side effects",
    requiredModules: ["Automation"],
    aiFeatures: ["AI Recommendations"],
    preview: previewGraph(
      "wf-approval-preview",
      "Approval Process",
      [
        { id: "d1", type: "trigger", catalogId: "tr-manual", label: "Manual Trigger", x: 72, y: 168 },
        { id: "d2", type: "ai_action", catalogId: "ai-rec", label: "AI Recommendations", x: 312, y: 168 },
        { id: "d3", type: "approval", catalogId: "el-approval", label: "Approval", x: 552, y: 168 },
        { id: "d4", type: "action", catalogId: "ac-notify", label: "Send Notification", x: 792, y: 168 },
      ],
      [
        { id: "w1", from: "d1", to: "d2" },
        { id: "w2", from: "d2", to: "d3" },
        { id: "w3", from: "d3", to: "d4" },
      ],
    ),
  },
];
