/**
 * Default AGXORA Agent catalog — marketplace + registry seed.
 */

import type { AgentDefinition, AgentId } from "../types";

export const DEFAULT_AGENTS: readonly AgentDefinition[] = [
  {
    id: "executive_advisor",
    name: "Executive Advisor",
    avatar: "EA",
    description: "Strategic briefings, KPI synthesis, and decision support.",
    role: "Executive Advisor",
    capabilities: ["strategy", "analysis", "reporting"],
    goals: ["Summarize business health", "Recommend priorities"],
    instructions:
      "Advise leadership with concise, evidence-backed recommendations.",
    tools: ["search", "finance", "projects", "crm", "notification"],
    permissions: ["agents.execute", "knowledge.read", "memory.read"],
    knowledgeSources: ["company", "projects", "crm", "policies"],
    marketplace: true,
    category: "Leadership",
  },
  {
    id: "sales_agent",
    name: "Sales Agent",
    avatar: "SA",
    description: "Pipeline coaching, outreach drafts, and deal next steps.",
    role: "Sales Agent",
    capabilities: ["outreach", "pipeline", "communication"],
    goals: ["Advance deals", "Prepare follow-ups"],
    instructions: "Prioritize revenue outcomes; respect CRM permissions.",
    tools: ["crm", "email", "calendar", "notification", "search"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["crm", "company", "procedures"],
    marketplace: true,
    category: "Revenue",
  },
  {
    id: "crm_assistant",
    name: "CRM Assistant",
    avatar: "CA",
    description: "Customer enrichment, hygiene, and relationship insights.",
    role: "CRM Assistant",
    capabilities: ["crm", "enrichment", "analysis"],
    goals: ["Keep customer data clean", "Surface account insights"],
    instructions: "Operate within CRM tool boundaries; never invent contacts.",
    tools: ["crm", "search", "notification", "email"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["crm", "documents", "policies"],
    marketplace: true,
    category: "CRM",
  },
  {
    id: "project_manager",
    name: "Project Manager",
    avatar: "PM",
    description: "Plans, task breakdowns, and delivery risk signals.",
    role: "Project Manager",
    capabilities: ["planning", "scheduling", "monitoring"],
    goals: ["Keep projects on track", "Flag blockers"],
    instructions: "Decompose goals into sequenced project steps.",
    tools: ["projects", "calendar", "notification", "workflow", "search"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["projects", "documents", "procedures"],
    marketplace: true,
    category: "Delivery",
  },
  {
    id: "workflow_coordinator",
    name: "Workflow Coordinator",
    avatar: "WC",
    description: "Triggers and orchestrates AGXORA automation workflows.",
    role: "Workflow Coordinator",
    capabilities: ["automation", "orchestration", "monitoring"],
    goals: ["Coordinate workflows", "Recover failed runs"],
    instructions: "Prefer workflow tool; escalate via supervisor when stuck.",
    tools: ["workflow", "integration", "notification", "api"],
    permissions: ["agents.execute", "tools.invoke", "agents.admin"],
    knowledgeSources: ["procedures", "policies", "company"],
    marketplace: true,
    category: "Automation",
  },
  {
    id: "finance_assistant",
    name: "Finance Assistant",
    avatar: "FA",
    description: "Invoice awareness, cashflow notes, and finance summaries.",
    role: "Finance Assistant",
    capabilities: ["finance", "analysis", "compliance"],
    goals: ["Summarize financial state", "Flag anomalies"],
    instructions: "Treat financial data as sensitive; isolate tools.",
    tools: ["finance", "documents", "search", "notification"],
    permissions: ["agents.execute", "knowledge.read", "memory.read"],
    knowledgeSources: ["company", "documents", "policies"],
    marketplace: true,
    category: "Finance",
  },
  {
    id: "document_analyst",
    name: "Document Analyst",
    avatar: "DA",
    description: "Extracts structure, risks, and summaries from documents.",
    role: "Document Analyst",
    capabilities: ["documents", "analysis", "extraction"],
    goals: ["Summarize documents", "Extract action items"],
    instructions: "Cite document sources; do not invent clauses.",
    tools: ["documents", "search", "notification"],
    permissions: ["agents.execute", "knowledge.read"],
    knowledgeSources: ["documents", "policies", "procedures"],
    marketplace: true,
    category: "Knowledge",
  },
  {
    id: "knowledge_assistant",
    name: "Knowledge Assistant",
    avatar: "KA",
    description: "Answers from company knowledge with RAG-ready retrieval.",
    role: "Knowledge Assistant",
    capabilities: ["rag", "search", "communication"],
    goals: ["Answer policy questions", "Route to source docs"],
    instructions: "Prefer knowledge engine; mark confidence when unsure.",
    tools: ["search", "documents", "notification"],
    permissions: ["agents.execute", "knowledge.read", "memory.read"],
    knowledgeSources: ["company", "documents", "policies", "vector", "rag"],
    marketplace: true,
    category: "Knowledge",
  },
  {
    id: "support_assistant",
    name: "Support Assistant",
    avatar: "SU",
    description: "Customer support triage, replies, and escalation paths.",
    role: "Support Assistant",
    capabilities: ["support", "communication", "triage"],
    goals: ["Resolve common issues", "Escalate complex cases"],
    instructions: "Be empathetic; escalate when confidence is low.",
    tools: ["crm", "email", "notification", "search", "documents"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["crm", "procedures", "documents"],
    marketplace: true,
    category: "Support",
  },
  {
    id: "meeting_assistant",
    name: "Meeting Assistant",
    avatar: "MA",
    description: "Agenda prep, note capture placeholders, and follow-ups.",
    role: "Meeting Assistant",
    capabilities: ["meetings", "summarization", "scheduling"],
    goals: ["Prepare agendas", "Capture follow-ups"],
    instructions: "Coordinate calendar and notifications carefully.",
    tools: ["calendar", "email", "notification", "documents", "search"],
    permissions: ["agents.execute", "tools.invoke", "memory.read"],
    knowledgeSources: ["projects", "crm", "company"],
    marketplace: true,
    category: "Productivity",
  },
  {
    id: "website_builder",
    name: "Website Builder",
    avatar: "WB",
    description: "Plans and generates structured website previews from a growth profile.",
    role: "Website Builder Agent",
    capabilities: ["website", "planning", "content"],
    goals: ["Generate website structure", "Prepare a reviewable preview"],
    instructions:
      "Generate structured website specifications only. Never claim a site is published without a publisher adapter success.",
    tools: ["website", "website_publish"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["company", "documents"],
    marketplace: true,
    category: "Growth",
  },
  {
    id: "social_media",
    name: "Social Media Agent",
    avatar: "SM",
    description: "Creates social strategy, calendars, and draft content pending approval.",
    role: "Social Media Agent",
    capabilities: ["social", "planning", "content"],
    goals: ["Create social strategy", "Plan a content calendar"],
    instructions:
      "Generate strategy and drafts only. Publishing and scheduling require approval and a real platform adapter.",
    tools: ["social", "social_publish", "social_schedule"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["company", "crm"],
    marketplace: true,
    category: "Growth",
  },
  {
    id: "growth_campaign",
    name: "Growth Campaign Agent",
    avatar: "GC",
    description: "Plans campaigns, evaluates readiness, and prepares execution behind approval.",
    role: "Growth Campaign Agent",
    capabilities: ["campaigns", "planning", "readiness"],
    goals: ["Plan a campaign", "Evaluate campaign readiness"],
    instructions:
      "Plan campaigns from growth data. Never claim execution success without a real adapter.",
    tools: ["campaign_plan", "campaign_readiness", "growth_insights", "campaign_execute"],
    permissions: ["agents.execute", "tools.invoke", "knowledge.read"],
    knowledgeSources: ["company", "crm"],
    marketplace: true,
    category: "Growth",
  },
  {
    id: "custom",
    name: "Custom Agent",
    avatar: "CU",
    description: "Extension point for organization-specific agents.",
    role: "Custom Agent",
    capabilities: ["custom"],
    goals: ["Execute custom instructions"],
    instructions: "Follow workspace-provided instructions and tool allowlist.",
    tools: ["api", "search", "notification", "mcp"],
    permissions: ["agents.execute", "tools.invoke"],
    knowledgeSources: ["company", "documents"],
    marketplace: false,
    category: "Custom",
  },
] as const;

export function getAgentDefinition(id: AgentId): AgentDefinition | undefined {
  return DEFAULT_AGENTS.find((a) => a.id === id);
}

export function listMarketplaceAgents(): readonly AgentDefinition[] {
  return DEFAULT_AGENTS.filter((a) => a.marketplace);
}
