import type {
  AiInsight,
  BankAccount,
  BankTransaction,
  DatevExportRecord,
  FinanceInvoice,
  FinanceOverviewMetric,
  SmartSearchExample,
  TaxDeadline,
  UploadJob,
  VatSummary,
} from "./types";
import { formatMoney } from "./format";

export const FINANCE_OVERVIEW: readonly FinanceOverviewMetric[] = [
  {
    id: "revenue",
    label: "Revenue",
    value: formatMoney(428650),
    caption: "Sample · last 30 days",
    delta: { value: "+8.4%", positive: true },
    tone: "positive",
  },
  {
    id: "expenses",
    label: "Expenses",
    value: formatMoney(186420),
    caption: "Sample · operating + COGS",
    delta: { value: "+2.1%", positive: false },
    tone: "default",
  },
  {
    id: "profit",
    label: "Profit",
    value: formatMoney(242230),
    caption: "Sample · net operating",
    delta: { value: "+12.6%", positive: true },
    tone: "positive",
  },
  {
    id: "vat-due",
    label: "VAT Due",
    value: formatMoney(18450),
    caption: "Sample · Q2 window",
    delta: { value: "Due in 12d", positive: false },
    tone: "warning",
  },
  {
    id: "open-invoices",
    label: "Open Invoices",
    value: "24",
    caption: "Sample · " + formatMoney(67280) + " outstanding",
    tone: "accent",
  },
  {
    id: "paid-invoices",
    label: "Paid Invoices",
    value: "148",
    caption: "Sample · this quarter",
    delta: { value: "+18", positive: true },
    tone: "positive",
  },
  {
    id: "cashflow",
    label: "Cashflow",
    value: formatMoney(94320),
    caption: "Sample · 30-day projection",
    delta: { value: "+4.2%", positive: true },
    tone: "positive",
  },
  {
    id: "ai-score",
    label: "AI Financial Score",
    value: "86 / 100",
    caption: "Sample score · not live risk scoring",
    delta: { value: "+3", positive: true },
    tone: "accent",
  },
];

export const FINANCE_INVOICES: readonly FinanceInvoice[] = [
  {
    id: "inv-1001",
    number: "INV-2026-1001",
    company: "Nordlicht GmbH",
    amount: 12400,
    vat: 2356,
    currency: "EUR",
    status: "open",
    dueDate: "2026-08-12",
    paymentStatus: "unpaid",
    category: "professional",
    aiConfidence: 96,
  },
  {
    id: "inv-1002",
    number: "INV-2026-1002",
    company: "Amazon Business EU",
    amount: 842.5,
    vat: 160.08,
    currency: "EUR",
    status: "paid",
    dueDate: "2026-07-18",
    paymentStatus: "paid",
    category: "office",
    aiConfidence: 99,
  },
  {
    id: "inv-1003",
    number: "INV-2026-1003",
    company: "Cloudflare Inc.",
    amount: 2190,
    vat: 416.1,
    currency: "EUR",
    status: "paid",
    dueDate: "2026-07-05",
    paymentStatus: "paid",
    category: "saas",
    aiConfidence: 94,
  },
  {
    id: "inv-1004",
    number: "INV-2026-1004",
    company: "Deutsche Bahn AG",
    amount: 486.2,
    vat: 92.38,
    currency: "EUR",
    status: "overdue",
    dueDate: "2026-07-22",
    paymentStatus: "unpaid",
    category: "travel",
    aiConfidence: 88,
  },
  {
    id: "inv-1005",
    number: "INV-2026-1005",
    company: "Meta Ads",
    amount: 5600,
    vat: 1064,
    currency: "EUR",
    status: "open",
    dueDate: "2026-08-01",
    paymentStatus: "partial",
    category: "marketing",
    aiConfidence: 91,
  },
  {
    id: "inv-1006",
    number: "INV-2026-1006",
    company: "Stadtwerke München",
    amount: 312.8,
    vat: 59.43,
    currency: "EUR",
    status: "open",
    dueDate: "2026-08-08",
    paymentStatus: "unpaid",
    category: "utilities",
    aiConfidence: 97,
  },
  {
    id: "inv-1007",
    number: "INV-2026-1007",
    company: "Stripe Payments",
    amount: 1890,
    vat: 359.1,
    currency: "EUR",
    status: "paid",
    dueDate: "2026-07-10",
    paymentStatus: "paid",
    category: "saas",
    aiConfidence: 95,
  },
  {
    id: "inv-1008",
    number: "INV-2026-1008",
    company: "Kanzlei Weber & Partner",
    amount: 3200,
    vat: 608,
    currency: "EUR",
    status: "draft",
    dueDate: "2026-08-20",
    paymentStatus: "unpaid",
    category: "professional",
    aiConfidence: 72,
  },
];

export const UPLOAD_JOBS: readonly UploadJob[] = [
  {
    id: "up-1",
    fileName: "amazon-july-receipt.pdf",
    source: "pdf",
    ocr: "pending",
    extraction: "pending",
    categorization: "pending",
    duplicateDetection: "pending",
    uploadedAt: "2026-07-28T09:12:00Z",
  },
  {
    id: "up-2",
    fileName: "hotel-berlin.jpg",
    source: "image",
    ocr: "pending",
    extraction: "pending",
    categorization: "pending",
    duplicateDetection: "pending",
    uploadedAt: "2026-07-29T14:40:00Z",
  },
  {
    id: "up-3",
    fileName: "invoice-forward.eml",
    source: "email",
    ocr: "skipped",
    extraction: "pending",
    categorization: "pending",
    duplicateDetection: "pending",
    uploadedAt: "2026-07-29T16:05:00Z",
  },
];

export const BANK_ACCOUNTS: readonly BankAccount[] = [
  {
    id: "ba-1",
    bankName: "Deutsche Bank Business",
    ibanMasked: "DE89 **** **** **** 3000",
    balance: 184250.4,
    currency: "EUR",
    connected: true,
    lastSync: "2026-07-29T18:20:00Z",
  },
  {
    id: "ba-2",
    bankName: "N26 Business",
    ibanMasked: "DE16 **** **** **** 1001",
    balance: 42890.12,
    currency: "EUR",
    connected: true,
    lastSync: "2026-07-29T17:55:00Z",
  },
  {
    id: "ba-3",
    bankName: "Commerzbank",
    ibanMasked: "DE75 **** **** **** 2200",
    balance: 0,
    currency: "EUR",
    connected: false,
    lastSync: "—",
  },
];

export const BANK_TRANSACTIONS: readonly BankTransaction[] = [
  {
    id: "tx-1",
    accountId: "ba-1",
    date: "2026-07-29",
    counterparty: "Nordlicht GmbH",
    amount: 12400,
    currency: "EUR",
    matched: false,
  },
  {
    id: "tx-2",
    accountId: "ba-1",
    date: "2026-07-28",
    counterparty: "Amazon Business EU",
    amount: -842.5,
    currency: "EUR",
    matched: true,
    invoiceRef: "INV-2026-1002",
  },
  {
    id: "tx-3",
    accountId: "ba-2",
    date: "2026-07-27",
    counterparty: "Cloudflare Inc.",
    amount: -2190,
    currency: "EUR",
    matched: true,
    invoiceRef: "INV-2026-1003",
  },
  {
    id: "tx-4",
    accountId: "ba-1",
    date: "2026-07-26",
    counterparty: "Meta Platforms Ireland",
    amount: -2800,
    currency: "EUR",
    matched: true,
    invoiceRef: "INV-2026-1005",
  },
  {
    id: "tx-5",
    accountId: "ba-2",
    date: "2026-07-25",
    counterparty: "Customer — Helios Labs",
    amount: 8900,
    currency: "EUR",
    matched: false,
  },
];

export const DATEV_EXPORTS: readonly DatevExportRecord[] = [
  {
    id: "exp-1",
    format: "datev",
    label: "DATEV Buchungsstapel Q2",
    createdAt: "2026-07-15T10:00:00Z",
    status: "delivered",
    period: "Q2 2026",
    steuerberaterReady: true,
  },
  {
    id: "exp-2",
    format: "csv",
    label: "Invoice ledger CSV",
    createdAt: "2026-07-28T08:30:00Z",
    status: "ready",
    period: "Jul 2026",
    steuerberaterReady: true,
  },
  {
    id: "exp-3",
    format: "xml",
    label: "VAT XML package",
    createdAt: "2026-07-29T11:15:00Z",
    status: "queued",
    period: "Jul 2026",
    steuerberaterReady: false,
  },
  {
    id: "exp-4",
    format: "pdf",
    label: "Steuerberater PDF pack",
    createdAt: "2026-07-20T14:00:00Z",
    status: "delivered",
    period: "Q2 2026",
    steuerberaterReady: true,
  },
];

export const VAT_SUMMARIES: readonly VatSummary[] = [
  {
    periodLabel: "July 2026",
    periodType: "monthly",
    collected: 21450,
    deductible: 8920,
    netDue: 12530,
    currency: "EUR",
  },
  {
    periodLabel: "Q2 2026",
    periodType: "quarterly",
    collected: 61200,
    deductible: 24780,
    netDue: 36420,
    currency: "EUR",
  },
];

export const TAX_DEADLINES: readonly TaxDeadline[] = [
  {
    id: "td-1",
    label: "Monthly VAT return",
    dueDate: "2026-08-10",
    amount: 12530,
    currency: "EUR",
    period: "monthly",
    status: "due_soon",
  },
  {
    id: "td-2",
    label: "Quarterly VAT settlement",
    dueDate: "2026-08-15",
    amount: 18450,
    currency: "EUR",
    period: "quarterly",
    status: "upcoming",
  },
  {
    id: "td-3",
    label: "Advance corporate tax",
    dueDate: "2026-09-10",
    amount: 28000,
    currency: "EUR",
    period: "annual",
    status: "upcoming",
  },
];

export const AI_INSIGHTS: readonly AiInsight[] = [
  {
    id: "ai-1",
    kind: "unusual_expense",
    title: "Unusual marketing spend",
    description: "Meta Ads is 42% above your 90-day baseline for the same category.",
    severity: "warning",
    detectedAt: "2026-07-29T12:00:00Z",
    actionLabel: "Review spend",
  },
  {
    id: "ai-2",
    kind: "duplicate_invoice",
    title: "Possible duplicate invoice",
    description: "INV-2026-1002 matches a prior Amazon receipt by amount and vendor fingerprint.",
    severity: "critical",
    detectedAt: "2026-07-28T16:20:00Z",
    actionLabel: "Compare",
  },
  {
    id: "ai-3",
    kind: "missing_invoice",
    title: "Missing supplier invoice",
    description: "Bank payment to Stadtwerke München has no linked document yet.",
    severity: "warning",
    detectedAt: "2026-07-27T09:40:00Z",
    actionLabel: "Request upload",
  },
  {
    id: "ai-4",
    kind: "late_payment",
    title: "Late payment risk",
    description: "Deutsche Bahn AG invoice is 7 days past due with no payment signal.",
    severity: "critical",
    detectedAt: "2026-07-29T08:00:00Z",
    actionLabel: "Chase payment",
  },
  {
    id: "ai-5",
    kind: "cashflow_prediction",
    title: "Cashflow outlook",
    description: "Projected net cash remains positive for 30 days if open receivables clear by Aug 12.",
    severity: "info",
    detectedAt: "2026-07-29T07:30:00Z",
    actionLabel: "View forecast",
  },
  {
    id: "ai-6",
    kind: "tax_optimization",
    title: "Tax optimization suggestion",
    description: "Prepaying Q3 SaaS licenses before Aug 31 may improve deductible timing for monthly VAT.",
    severity: "opportunity",
    detectedAt: "2026-07-28T11:00:00Z",
    actionLabel: "See suggestion",
  },
];

export const SMART_SEARCH_EXAMPLES: readonly SmartSearchExample[] = [
  {
    id: "q1",
    query: "Show unpaid invoices",
    description: "Open receivables with unpaid or partial status",
  },
  {
    id: "q2",
    query: "Show July expenses",
    description: "Expense-side invoices and bank outflows in July",
  },
  {
    id: "q3",
    query: "Find Amazon invoices",
    description: "Vendor match across invoice center and uploads",
  },
  {
    id: "q4",
    query: "Export VAT",
    description: "Jump to DATEV / tax export actions",
  },
];
